Sorgente/src/objects/Contact.object
<CustomObject>
    <recordTypes>
        <fullName>Specialista</fullName>
        <active>true</active>
        <description>Uno medico con caratteristiche da influencer</description>
        <label>Specialista</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

Sorgente/src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>CAP_fatturazione__c</fullName>
        <label>CAP fatturazione</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CAP_spedizione__c</fullName>
        <label>CAP</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Citt_fatturazione__c</fullName>
        <label>Città fatturazione</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Citt_spedizione__c</fullName>
        <label>Città</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Codice_fiscale_fatturazione__c</fullName>
        <label>Codice fiscale fatturazione</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Data_di_desiderata_ricezione__c</fullName>
        <label>Data di ricezione kit</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Data_di_spedizione_desiderata__c</fullName>
        <label>Data di spedizione kit</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Data_presunta_parto__c</fullName>
        <label>Data presunta parto</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Data_ricontatto_preparto__c</fullName>
        <label>Data ricontatto preparto</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Data_spedizione_kit_da_decidere__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Data spedizione kit da decidere</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Descrizione_ricontatto_preparto__c</fullName>
        <label>Note ricontatto preparto</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Ginecologo_non_ancora_deciso__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Ginecologo non ancora deciso</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Metodo_di_pagamento_kit__c</fullName>
        <label>Metodo di pagamento</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Bonifico</fullName>
                </value>
                <value>
                    <fullName>Carta di credito</fullName>
                </value>
                <value>
                    <fullName>PayPal</fullName>
                </value>
                <value>
                    <fullName>Giroconto postale</fullName>
                </value>
                <value>
                    <fullName>Contanti o assegno alla consegna</fullName>
                </value>
                <value>
                    <fullName>Contanti</fullName>
                </value>
                <value>
                    <fullName>Assegno</fullName>
                </value>
                <value>
                    <fullName>Bollettino postale</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Nome_Fatturazione__c</fullName>
        <label>Nome Fatturazione</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Nome_Numero_citofono__c</fullName>
        <label>Nome spedizione</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Numero_di_telefono_spedizione__c</fullName>
        <label>Numero di telefono spedizione</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Origine_in_fase_di_ordine__c</fullName>
        <label>Origine in fase di ordine</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Altro</fullName>
                </value>
                <value>
                    <fullName>Amici/conoscenti</fullName>
                </value>
                <value>
                    <fullName>Collaboratore</fullName>
                </value>
                <value>
                    <fullName>Corso Preparto</fullName>
                </value>
                <value>
                    <fullName>Cross selling</fullName>
                </value>
                <value>
                    <fullName>Cross selling - Aurora</fullName>
                </value>
                <value>
                    <fullName>Da verificare</fullName>
                </value>
                <value>
                    <fullName>Fiera</fullName>
                    <label>Fiere e Convegni</label>
                </value>
                <value>
                    <fullName>Già cliente</fullName>
                </value>
                <value>
                    <fullName>Giornali/riviste</fullName>
                </value>
                <value>
                    <fullName>KAM</fullName>
                </value>
                <value>
                    <fullName>Motore di ricerca</fullName>
                </value>
                <value>
                    <fullName>Pieghevole</fullName>
                </value>
                <value>
                    <fullName>Professional</fullName>
                </value>
                <value>
                    <fullName>Programma Amico</fullName>
                </value>
                <value>
                    <fullName>Siti e app satellite</fullName>
                </value>
                <value>
                    <fullName>Siti extra gruppo</fullName>
                </value>
                <value>
                    <fullName>Social media</fullName>
                </value>
                <value>
                    <fullName>Specialista</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Ospedale_Punto_prelievo__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Ospedale/Punto prelievo</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Professional</value>
            </filterItems>
            <filterItems>
                <field>Account.Struttura_abilitata_ai_parti__c</field>
                <operation>equals</operation>
                <value>Si</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Opportunità (Ospedale/Punto prelievo)</relationshipLabel>
        <relationshipName>Opportunit1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Ospedale_non_ancora_deciso__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Ospedale non ancora deciso</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Regione_Parto__c</fullName>
        <label>Regione Parto</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Emilia Romagna</fullName>
                </value>
                <value>
                    <fullName>Altra</fullName>
                </value>
                <value>
                    <fullName>Emilia Romgna</fullName>
                    <isActive>false</isActive>
                    <label>Emilia Romgna</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Tipo_parto__c</fullName>
        <label>Tipo parto</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Singolo</fullName>
                </value>
                <value>
                    <fullName>Gemellare</fullName>
                </value>
                <value>
                    <fullName>Trigemellare</fullName>
                </value>
                <value>
                    <fullName>Quadrigemellare</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Via_fatturazione__c</fullName>
        <label>Via fatturazione</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Via_spedizione__c</fullName>
        <label>Indirizzo</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

Sorgente/.apex/src/objects/Ruolo_degli_Specialisti_Collaboratori__c.object
<CustomObject>
    <fields>
        <fullName>Opportunita__c</fullName>
        <label>Opportunità</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Ruoli degli Specialisti/Collaboratori</relationshipLabel>
        <relationshipName>Ruoli_degli_Specialisti_Collaboratori</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Ruolo__c</fullName>
        <label>Ruolo</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Specialista che consiglia</fullName>
                </value>
                <value>
                    <fullName>Specialista</fullName>
                </value>
                <value>
                    <fullName>Collaboratore che consiglia</fullName>
                </value>
                <value>
                    <fullName>Programma Amico</fullName>
                </value>
                <value>
                    <fullName>Operatore prelievo</fullName>
                </value>
                <value>
                    <fullName>Prescrittore</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Ruolo degli Specialisti/Collaboratori</label>
    <nameField>
        <displayFormat>A-{0000000}</displayFormat>
        <label>Nome Ruolo degli Specialisti/Collaborato</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Ruoli degli Specialisti/Collaboratori</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Sorgente/.apex/src/classes/VerificaOrdine.cls
global class VerificaOrdine {
    webservice static String verificaOrdine(string OpportunityId){
		Opportunity opp = [Select RecordTypeId, StageName, Data_di_desiderata_ricezione__c, Data_di_spedizione_desiderata__c, Data_spedizione_kit_da_decidere__c,
                           Metodo_di_pagamento_kit__c, Regione_Parto__c, Data_presunta_parto__c, Tipo_parto__c, Codice_fiscale_fatturazione__c,
                           Via_fatturazione__c, CAP_fatturazione__c, Citt_fatturazione__c, Nome_Fatturazione__c,
                           Via_spedizione__c, CAP_spedizione__c, Citt_spedizione__c, Nome_Numero_citofono__c,
                           Numero_di_telefono_spedizione__c, Origine_in_fase_di_ordine__c, Data_ricontatto_preparto__c, Descrizione_ricontatto_preparto__c,
                           Ospedale_Punto_prelievo__c, Ospedale_non_ancora_deciso__c, Ginecologo_non_ancora_deciso__c
                           from Opportunity where Id= :OpportunityId];
        return getWarningMessage(opp);
    }
    
    public static string getWarningMessage(Opportunity opp) {
        if(opp==null) {
            return 'Id opportunità non valido';
        }
        if(opp.RecordTypeId != AppSetup.recordTypeSS){
        	return 'L\'opportunità non è di Sorgente Staminali';
        }
        if(opp.StageName!='Aperto'){
            return 'L\'opportunità non è in stato "Aperto"';
        }

        String warn='';
        if(opp.Data_di_desiderata_ricezione__c == null && opp.Data_spedizione_kit_da_decidere__c!=true){
            if(warn!='') warn+=', ';
            warn+='la Data di ricezione';
        }               
        if(opp.Data_di_spedizione_desiderata__c == null && opp.Data_spedizione_kit_da_decidere__c!=true){
            if(warn!='') warn+=', ';
            warn+='la Data di spedizione';
        }            
        if(opp.Metodo_di_pagamento_kit__c == null){
            if(warn!='') warn+=', ';
            warn+='la Modalità pagamento kit';
        }
        if(opp.Regione_Parto__c == null){
            if(warn!='') warn+=', ';
            warn+='la Regione parto';
        }
        if(opp.Data_presunta_parto__c == null){
            if(warn!='') warn+=', ';
            warn+='la data presunta del parto';
        }
        if(opp.Tipo_parto__c == null){
            if(warn!='') warn+=', ';
            warn+=' il Tipo parto';
        }           
        if(opp.Codice_fiscale_fatturazione__c == null){
            if(warn!='') warn+=', ';
            warn+='il Codice fiscale fatturazione';
        }
        // Indirizzi: testare via, cap, città e citofono (contatto sped)
        if(opp.Via_fatturazione__c == null || opp.CAP_fatturazione__c == null || opp.Citt_fatturazione__c == null || opp.Nome_Fatturazione__c == null){
            if(warn!='') warn+=', ';
            warn+='l\'indirizzo di fatturazione';
        }
        if(opp.Via_spedizione__c == null || opp.CAP_spedizione__c == null || opp.Citt_spedizione__c == null || opp.Nome_Numero_citofono__c == null){
            if(warn!='') warn+=', ';
            warn+='l\'indirizzo di spedizione';
        }
        if(opp.Numero_di_telefono_spedizione__c == null){
            if(warn!='') warn+=', ';
            warn+='il Numero di telefono spedizione';
        }
        if(opp.Origine_in_fase_di_ordine__c == null){
            if(warn!='') warn+=', ';
            warn+='l\'origine al momento dell\'ordine';
        }
        if(opp.Data_ricontatto_preparto__c == null){
            if(warn!='') warn+=', ';
            warn+='la data di ricontatto preparto';
        }
        if(opp.Descrizione_ricontatto_preparto__c == null){
            if(warn!='') warn+=', ';
            warn+='la descrizione di ricontatto preparto';
        }
        if(opp.Ospedale_Punto_prelievo__c == null && opp.Ospedale_non_ancora_deciso__c != true){
            if(warn!='') warn+=', ';
            warn+='l\'ospedale';
        }            
        boolean hasGinecologo = opp.Ginecologo_non_ancora_deciso__c == true;
        if(!hasGinecologo && [select Id from Ruolo_degli_Specialisti_Collaboratori__c where Ruolo__c='Specialista' and opportunita__c=:opp.Id].size()<=0){
            if(warn!='') warn+=', ';
            warn+='il ginecologo';                
        }
        
        boolean hasParent = false;
        boolean hasTelefono = false;
        for(OpportunityContactRole r : [SELECT Id, Role, Contact.Phone from OpportunityContactRole where OpportunityId = :opp.id]){
            if(r.Role == 'Padre' || r.Role == 'Madre'){
                hasParent = true;
                if(r.Contact.Phone !=null){
                    hasTelefono = true;
                    break;
                }
            }
        }
        if(!hasParent){
            if(warn!='') warn+=', ';
            warn+='sia il padre che la madre in ruolo dei referenti';                
        } else if(!hasTelefono){
            if(warn!='') warn+=', ';
            warn+='il numero di telefono di almeno uno dei genitori';                
        }
        
        // Prodotti
        boolean hasKit = false;
        boolean hasAnalisi = false;
        boolean hasCanone = false;
        
        for(OpportunityLineItem k : [SELECT Id, Quantity, Product2Id, ProductCode from OpportunityLineItem where OpportunityId = :opp.id]){
            if(AppSetup.KitCodes.contains(k.ProductCode) && k.Quantity > 0) hasKit = true;
            if(AppSetup.KitAnalisi.contains(k.ProductCode) && k.Quantity > 0) hasAnalisi = true;
            if(AppSetup.KitConservazione.contains(k.ProductCode) && k.Quantity > 0) hasCanone = true;
        }
        if(!hasKit){
            if(warn!='') warn+=', ';
            warn+='il KIT Staminali standard';                
        }
        if(!hasAnalisi){
            if(warn!='') warn+=', ';
            warn+='l\'Analisi di laboratorio del campione di sangue cordonale';                
        }
        if(!hasCanone){
            if(warn!='') warn+=', ';
            warn+='il Canone di conservazione ventennale del campione';                
        }
        
        if(warn!=''){         
            return 'Manca ' + warn;
        } else {
            return 'Ok';
        }
    }
}
/*
"Campi obligatori:
x ""Ruoli dei referenti"" almeno Madre o Padre
x ""Tipo parto""
x almeno 1 ""Ruolo dei referenti"" con email o telefono
x ""indirizzo fatturazione""
x ""indirizzo Spedizione""
x ""contatto spedizione""
x ""contatto fatturazione""
x Prodotti deve contenere almeno: ""kit"" ""analisi di laboratorio"" e ""canone di conservazione""
x Modalità pagamento kit
x Regione parto
x ""Codice fiscale fatturazione""
x ""origine al momento dell'ordine"""
*/
/*
x Data presunta parto
x Numero di telefono spedizione
x data di ricontatto preparto
x descrizione di ricontatto preparto
x Ospedale Punto prelievo
*/