Sorgente/src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Conferma_perdita_SG__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Conferma perdita SG</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Conferma_perdita_SS__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Conferma perdita SS</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Listino_prezzi__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Listino prezzi</label>
        <referenceTo>Pricebook2</referenceTo>
        <relationshipLabel>Referenti</relationshipLabel>
        <relationshipName>Referenti</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Max_Opportunit_SG_60__c</fullName>
        <label>Max Opportunità SG (60)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Max_Opportunit_SS_90__c</fullName>
        <label>Max Opportunità SS (90)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Motivazione_perdita_SG__c</fullName>
        <label>Motivazione perdita SG</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Prezzo prodotti</fullName>
                </value>
                <value>
                    <fullName>Qualità prodotti</fullName>
                </value>
                <value>
                    <fullName>Qualità servizio</fullName>
                </value>
                <value>
                    <fullName>Listino incompleto</fullName>
                </value>
                <value>
                    <fullName>Altro</fullName>
                </value>
                <value>
                    <fullName>Inattivo</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Motivazione_perdita_SS__c</fullName>
        <label>Motivazione perdita SS</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Pro-donazione</fullName>
                </value>
                <value>
                    <fullName>Esclusività con competitor</fullName>
                </value>
                <value>
                    <fullName>Qualità prodotto</fullName>
                </value>
                <value>
                    <fullName>Qualità servizio</fullName>
                </value>
                <value>
                    <fullName>Prezzo servizio al paziente</fullName>
                </value>
                <value>
                    <fullName>Punti consiglio bassi</fullName>
                </value>
                <value>
                    <fullName>Altro</fullName>
                </value>
                <value>
                    <fullName>Inattivo</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Opportunit_SG_60__c</fullName>
        <label>Opportunità SG (60)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Opportunit_SS_90__c</fullName>
        <label>Opportunità SS (90)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Status_SG__c</fullName>
        <label>Status SG</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Da affiliare o associare</fullName>
                </value>
                <value>
                    <fullName>Da riaffiliare</fullName>
                </value>
                <value>
                    <fullName>Da riassociare</fullName>
                </value>
                <value>
                    <fullName>Associato</fullName>
                </value>
                <value>
                    <fullName>Affiliato</fullName>
                </value>
                <value>
                    <fullName>Inattivo</fullName>
                </value>
                <value>
                    <fullName>Associato perso</fullName>
                </value>
                <value>
                    <fullName>Affiliato perso</fullName>
                </value>
                <value>
                    <fullName>Perso</fullName>
                </value>
                <value>
                    <fullName>IA prodotto</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Status_SS__c</fullName>
        <label>Status SS</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Da affiliare o associare</fullName>
                </value>
                <value>
                    <fullName>Da riaffiliare</fullName>
                </value>
                <value>
                    <fullName>Da riassociare</fullName>
                </value>
                <value>
                    <fullName>Associato</fullName>
                </value>
                <value>
                    <fullName>Affiliato</fullName>
                </value>
                <value>
                    <fullName>Inattivo</fullName>
                </value>
                <value>
                    <fullName>Associato perso</fullName>
                </value>
                <value>
                    <fullName>Affiliato perso</fullName>
                </value>
                <value>
                    <fullName>Perso</fullName>
                </value>
                <value>
                    <fullName>IA prodotto</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <recordTypes>
        <fullName>Specialista</fullName>
        <active>true</active>
        <description>Uno medico con caratteristiche da influencer</description>
        <label>Specialista</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

Sorgente/.apex/src/objects/Pricebook2.object
<CustomObject>
    <fields>
        <fullName>Punti_Consiglio_SS__c</fullName>
        <label>Punti Consiglio SS</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Tipo_Listino__c</fullName>
        <label>Tipo listino</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Punti consiglio</fullName>
                </value>
                <value>
                    <fullName>Acquisto</fullName>
                </value>
                <value>
                    <fullName>Libero</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ReadSelect</sharingModel>
</CustomObject>

Sorgente/.apex/src/objects/Ruolo_degli_Specialisti_Collaboratori__c.object
<CustomObject>
    <fields>
        <fullName>Opportunita__c</fullName>
        <label>Opportunità</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Ruoli degli Specialisti/Collaboratori</relationshipLabel>
        <relationshipName>Ruoli_degli_Specialisti_Collaboratori</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Referente__c</fullName>
        <label>Referente</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.RecordType.DeveloperName</field>
                <operation>equals</operation>
                <value>Specialista</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Ruoli degli Specialisti/Collaboratori</relationshipLabel>
        <relationshipName>Ruoli_degli_Specialisti_Collaboratori</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Ruolo__c</fullName>
        <label>Ruolo</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Specialista che consiglia</fullName>
                </value>
                <value>
                    <fullName>Specialista</fullName>
                </value>
                <value>
                    <fullName>Collaboratore che consiglia</fullName>
                </value>
                <value>
                    <fullName>Programma Amico</fullName>
                </value>
                <value>
                    <fullName>Operatore prelievo</fullName>
                </value>
                <value>
                    <fullName>Prescrittore</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Ruolo degli Specialisti/Collaboratori</label>
    <nameField>
        <displayFormat>A-{0000000}</displayFormat>
        <label>Nome Ruolo degli Specialisti/Collaborato</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Ruoli degli Specialisti/Collaboratori</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Sorgente/.apex/src/classes/UpdateStatusReferenti.cls
public class UpdateStatusReferenti {
    public void execute(){
        List<Contact> contacts = [Select Id, Status_SG__c, Status_SS__c, Opportunit_SG_60__c, 
                                  Opportunit_SS_90__c, Motivazione_perdita_SG__c, Motivazione_perdita_SS__c, 
                                  Listino_prezzi__c, Max_Opportunit_SG_60__c, Max_Opportunit_SS_90__c, Conferma_perdita_SS__c,Conferma_perdita_SG__c 
                                  from Contact where IsPersonAccount = false and RecordTypeId = :AppSetup.recordTypeSpecialista];
        for(contact r: contacts){
            Integer sg_60 = [Select Opportunita__r.Id from Ruolo_degli_Specialisti_Collaboratori__c 
                             where Referente__c = :r.Id 
                             and (Ruolo__c = 'Specialista' or Ruolo__c = 'Specialista che consiglia') 
                             and Opportunita__r.RecordTypeId = :AppSetup.recordTypeSG
                             and  Opportunita__r.StageName != 'Chiuso da ripetere'
                             and Opportunita__r.CreatedDate = LAST_N_DAYS:60
                             GROUP BY Opportunita__r.Id].size();
            r.Opportunit_SG_60__c = sg_60;
            Integer max_sg_60 = r.Max_Opportunit_SG_60__c == null ? 0 : (Integer)r.Max_Opportunit_SG_60__c;
            if(sg_60 > max_sg_60){
                r.Max_Opportunit_SG_60__c = sg_60;
                max_sg_60 = sg_60;
            }
            
            Integer ss_90 = [Select Opportunita__r.Id from Ruolo_degli_Specialisti_Collaboratori__c 
                             where Referente__c = :r.Id 
                             and (Ruolo__c = 'Specialista' or Ruolo__c = 'Specialista che consiglia') 
                             and Opportunita__r.RecordTypeId = :AppSetup.recordTypeSS
                             and  Opportunita__r.StageName != 'Chiuso da ripetere'
                             and Opportunita__r.CreatedDate = LAST_N_DAYS:90
                             GROUP BY Opportunita__r.Id].size();
            r.Opportunit_SS_90__c = ss_90;
            Integer max_ss_90 = r.Max_Opportunit_SS_90__c == null ? 0 : (Integer)r.Max_Opportunit_SS_90__c;
            if(ss_90 > max_ss_90){
                r.Max_Opportunit_SS_90__c = ss_90;
                max_ss_90 = ss_90;
            }           
            
            // change statuses?
            // TODO: Optimize
            if(r.Listino_prezzi__c != null && 
               	( ((r.Status_SG__c == 'Da affiliare o associare' || r.Status_SG__c == 'Affiliato' || r.Status_SG__c == 'Associato') && sg_60 > 0 ) || 
                  ((r.Status_SS__c == 'Da affiliare o associare' || r.Status_SS__c == 'Affiliato' || r.Status_SS__c == 'Associato') && ss_90 > 0 ) 
                )
              ){
                Pricebook2 listino = [SELECT Id, Tipo_Listino__c, Punti_Consiglio_SS__c FROM Pricebook2 where id =:r.Listino_prezzi__c].get(0);
                if((r.Status_SG__c == 'Da affiliare o associare' || r.Status_SG__c == 'Affiliato' || r.Status_SG__c == 'Associato') && sg_60 > 0 ){
                    if(listino.Tipo_Listino__c == 'Libero') {
                        r.Status_SG__c = 'Affiliato';
                    } else {
                    	r.Status_SG__c = 'Associato';
                    }
                }
                
                if((r.Status_SS__c == 'Da affiliare o associare' || r.Status_SS__c == 'Affiliato' || r.Status_SS__c == 'Associato') && ss_90 > 0 ){
                    if(listino.Punti_Consiglio_SS__c == null || listino.Punti_Consiglio_SS__c == 0) {
                        r.Status_SS__c = 'Affiliato';
                    } else {
                    	r.Status_SS__c = 'Associato';
                    }
                }            	
            }
       
            if(r.Status_SG__c == 'Affiliato' && max_sg_60 != 0 && ( (1.0 * max_sg_60 - sg_60) / max_sg_60) >= .3  ){ r.Status_SG__c = 'Da riaffiliare'; } 
            else if(r.Status_SG__c == 'Da riaffiliare' && max_sg_60 != 0 && ( (1.0 * max_sg_60 - sg_60) / max_sg_60) < .3  ){ r.Status_SG__c = 'Affiliato'; } 
            else if(r.Status_SG__c == 'Associato' && max_sg_60 != 0 && ( (1.0 * max_sg_60 - sg_60) / max_sg_60) >= .3  ){ r.Status_SG__c = 'Da riassociare'; } 
            else if(r.Status_SG__c == 'Da riassociare' && max_sg_60 != 0 && ( (1.0 * max_sg_60 - sg_60) / max_sg_60) < .3  ){ r.Status_SG__c = 'Associato'; }
 
            if(r.Status_SS__c == 'Affiliato' && max_ss_90 != 0 && ( (1.0 * max_ss_90 - ss_90) / max_ss_90) >= .3  ){ r.Status_SS__c = 'Da riaffiliare'; } 
            else if(r.Status_SS__c == 'Da riaffiliare' && max_ss_90 != 0 && ( (1.0 * max_ss_90 - ss_90) / max_ss_90) < .3  ){ r.Status_SS__c = 'Affiliato'; } 
            else if(r.Status_SS__c == 'Associato' && max_ss_90 != 0 && ( (1.0 * max_ss_90 - ss_90) / max_ss_90) >= .3  ){ r.Status_SS__c = 'Da riassociare'; } 
            else if(r.Status_SS__c == 'Da riassociare' && max_ss_90 != 0 && ( (1.0 * max_ss_90 - ss_90) / max_ss_90) < .3  ){ r.Status_SS__c = 'Associato'; }

            
            if(r.Motivazione_perdita_SG__c != 'Inattivo' && r.Conferma_perdita_SG__c == true){
                if(r.Status_SG__c == 'Associato' || r.Status_SG__c == 'Da riassociare') r.Status_SG__c = 'Associato perso';
                if(r.Status_SG__c == 'Affiliato' || r.Status_SG__c == 'Da riaffiliare') r.Status_SG__c = 'Affiliato perso';
                if(r.Status_SG__c == 'Da affiliare o associare') r.Status_SG__c = 'Perso';
            }
            if(r.Motivazione_perdita_SG__c == 'Inattivo' && r.Conferma_perdita_SG__c == true){
                r.Status_SG__c = 'Inattivo';
            }
            if(r.Motivazione_perdita_SS__c != 'Inattivo' && r.Conferma_perdita_SS__c == true){
                if(r.Status_SS__c == 'Associato' || r.Status_SS__c == 'Da riassociare') r.Status_SS__c = 'Associato perso';
                if(r.Status_SS__c == 'Affiliato' || r.Status_SS__c == 'Da riaffiliare') r.Status_SS__c = 'Affiliato perso';
                if(r.Status_SS__c == 'Da affiliare o associare') r.Status_SS__c = 'Perso';
            }
            if(r.Motivazione_perdita_SS__c == 'Inattivo' && r.Conferma_perdita_SS__c == true){
                r.Status_SS__c = 'Inattivo';
            }
            
            update(r);
        }

   
    }
}