Sorgente/src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Addizionali_mese_precedente__c</fullName>
        <label>Addizionali mese precedente</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Numero_prelievi_ultimo_mese__c</fullName>
        <label>Numero prelievi ultimo mese</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

Sorgente/src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Addizionale_trasferta_Op_Pre__c</fullName>
        <label>Addizionale trasferta Op. Pre</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Data_ora_prelievo_effettiva__c</fullName>
        <label>Data/ora prelievo effettiva</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Operatore_prelievo__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Operatore prelievo</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.Categoria_collaboratore__c</field>
                <operation>equals</operation>
                <value>Operatore prelievo</value>
            </filterItems>
            <filterItems>
                <field>$Source.Provincia_spedizione__c</field>
                <operation>equals</operation>
                <valueField>Contact.MailingState</valueField>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Prelievi effettuati</relationshipLabel>
        <relationshipName>Opportunit</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

Sorgente/.apex/src/objects/Ruolo_degli_Specialisti_Collaboratori__c.object
<CustomObject>
    <fields>
        <fullName>Opportunita__c</fullName>
        <label>Opportunità</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Ruoli degli Specialisti/Collaboratori</relationshipLabel>
        <relationshipName>Ruoli_degli_Specialisti_Collaboratori</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Referente__c</fullName>
        <label>Referente</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.RecordType.DeveloperName</field>
                <operation>equals</operation>
                <value>Specialista</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Ruoli degli Specialisti/Collaboratori</relationshipLabel>
        <relationshipName>Ruoli_degli_Specialisti_Collaboratori</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Ruolo__c</fullName>
        <label>Ruolo</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Specialista che consiglia</fullName>
                </value>
                <value>
                    <fullName>Specialista</fullName>
                </value>
                <value>
                    <fullName>Collaboratore che consiglia</fullName>
                </value>
                <value>
                    <fullName>Programma Amico</fullName>
                </value>
                <value>
                    <fullName>Operatore prelievo</fullName>
                </value>
                <value>
                    <fullName>Prescrittore</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Ruolo degli Specialisti/Collaboratori</label>
    <nameField>
        <displayFormat>A-{0000000}</displayFormat>
        <label>Nome Ruolo degli Specialisti/Collaborato</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Ruoli degli Specialisti/Collaboratori</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Sorgente/src/classes/CalcoloPrelievi.cls
public class CalcoloPrelievi {
    public void execute(){
        // Recuperare per il mese precedente, per ogni operatore prelievo, 
        // il numero di prelievi (opportunità) e rimborsi oltre i 50km (Addizionale_trasferta_Op_Pre__c)
        // Numero_prelievi_ultimo_mese__c, 	Addizionali_mese_precedente__c
        
        List<AggregateResult> op = [Select Operatore_prelievo__c from Opportunity where Data_ora_prelievo_effettiva__c = LAST_MONTH GROUP BY Operatore_prelievo__c];
            /*[Select Referente__c from Ruolo_degli_Specialisti_Collaboratori__c 
                                                          where Ruolo__c = 'Operatore prelievo'
                                                          and Opportunita__r.Data_ora_prelievo_effettiva__c = LAST_MONTH
                                                          GROUP BY Referente__c];*/
        for (AggregateResult ar : op){
            String refId = (String)ar.get('Operatore_prelievo__c'); //  'Referente__c'          
            List<AggregateResult> pr = [Select count(Id) Num, SUM(Addizionale_trasferta_Op_Pre__c) TotAdd 
                                        from Opportunity 
                                        where Data_ora_prelievo_effettiva__c = LAST_MONTH 
                                        and Operatore_prelievo__c =:refId];
                /*[Select count(Id) Num, SUM(Opportunita__r.Addizionale_trasferta_Op_Pre__c) TotAdd
                                        from Ruolo_degli_Specialisti_Collaboratori__c
                                        where Ruolo__c = 'Operatore prelievo'
                                        and Opportunita__r.Data_ora_prelievo_effettiva__c = LAST_MONTH
                                        and Referente__c =:refId
                                       ];*/
            AggregateResult agg = pr.get(0);
            // System.debug(agg.get('Num') + ' ' + agg.get('TotAdd'));
            Contact r = [SELECT Id, Numero_prelievi_ultimo_mese__c, Addizionali_mese_precedente__c FROM Contact where Id=:refId];
            r.Numero_prelievi_ultimo_mese__c = (agg.get('Num') == null) ? 0 :(Decimal)agg.get('Num');
            r.Addizionali_mese_precedente__c = (agg.get('TotAdd') == null) ? 0 :(Decimal)agg.get('TotAdd');
            Update(r);
        }

    }
}