Sorgente/src/objects/Lead.object
<CustomObject>
    <fields>
        <fullName>Data_ora_ricontatto__c</fullName>
        <label>Data/ora ricontatto</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Fascia_Oraria__c</fullName>
        <label>Fascia Oraria</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Note__c</fullName>
        <label>Note</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Origine__c</fullName>
        <label>Origine</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Altro</fullName>
                </value>
                <value>
                    <fullName>Amici/conoscenti</fullName>
                </value>
                <value>
                    <fullName>Collaboratore</fullName>
                </value>
                <value>
                    <fullName>Corso Preparto</fullName>
                </value>
                <value>
                    <fullName>cross_selling_aurora</fullName>
                    <label>Cross selling - Aurora</label>
                </value>
                <value>
                    <fullName>Da verificare</fullName>
                </value>
                <value>
                    <fullName>Fiera</fullName>
                </value>
                <value>
                    <fullName>Già cliente</fullName>
                </value>
                <value>
                    <fullName>Giornali/riviste</fullName>
                </value>
                <value>
                    <fullName>KAM</fullName>
                </value>
                <value>
                    <fullName>Motore di ricerca</fullName>
                </value>
                <value>
                    <fullName>Pieghevole</fullName>
                </value>
                <value>
                    <fullName>Professional</fullName>
                </value>
                <value>
                    <fullName>Programma Amico</fullName>
                </value>
                <value>
                    <fullName>Siti e app satellite</fullName>
                </value>
                <value>
                    <fullName>Siti extra gruppo</fullName>
                </value>
                <value>
                    <fullName>Social media</fullName>
                </value>
                <value>
                    <fullName>Specialista</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Richiesta_guida__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Richiesta guida cartacea</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Sottocategoria_origine__c</fullName>
        <label>Sottocategoria origine</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Origine__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>CSCO</fullName>
                </value>
                <value>
                    <fullName>Ok Corso Preparto</fullName>
                </value>
                <value>
                    <fullName>CCS</fullName>
                </value>
                <value>
                    <fullName>Diagnosi prenatale</fullName>
                </value>
                <value>
                    <fullName>BRCA</fullName>
                </value>
                <value>
                    <fullName>Baby&apos;s Voice</fullName>
                </value>
                <value>
                    <fullName>Facebook</fullName>
                </value>
                <value>
                    <fullName>Twitter</fullName>
                </value>
                <value>
                    <fullName>Instagram</fullName>
                </value>
                <value>
                    <fullName>Bimbinfiera</fullName>
                </value>
                <value>
                    <fullName>i-Mamma</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ReadWriteTransfer</sharingModel>
</CustomObject>

Sorgente/.apex/src/objects/LeadQueue__c.object
<CustomObject>
    <fields>
        <fullName>Cap__c</fullName>
        <label>Cap</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Citta__c</fullName>
        <label>Città</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Cognome__c</fullName>
        <label>Cognome</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Data_ricontatto__c</fullName>
        <label>Data ricontatto</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Fascia_Oraria__c</fullName>
        <label>Fascia Oraria</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Nazione__c</fullName>
        <label>Nazione</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Nome__c</fullName>
        <label>Nome</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Note__c</fullName>
        <label>Note</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Origine__c</fullName>
        <label>Origine</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Provincia__c</fullName>
        <label>Provincia</label>
        <length>150</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Richiesta_guida_cartacea__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Richiesta guida cartacea</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Sottocategoria_origine__c</fullName>
        <label>Sottocategoria origine</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Telefono__c</fullName>
        <label>Telefono</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Via__c</fullName>
        <label>Via</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <label>LeadQueue</label>
    <nameField>
        <displayFormat>LQ-{000000000}</displayFormat>
        <label>Nome LeadQueue</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>LeadQueue</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Sorgente/.apex/src/classes/WebForms.cls
global class WebForms {
	webService static string CompleteLead(string nome, string cognome, string email, 
                                           string via, string cap, string citta, string provincia, string nazione,
                                           string telefono, date data_ricontatto, string fascia_oraria,
                                           string origine, string sottocategoria_origine, string note, boolean richiesta_guida_cartacea) {
        List<LeadQueue__c> dl = [SELECT Id from LeadQueue__c where Nome__c=:nome and Cognome__c=:cognome and email__c=:email];
        if(dl.size() > 0){
            return 'Dati Lead già in coda';
        }
        try{
            LeadQueue__c nq = new LeadQueue__c(Nome__c=nome, Cognome__c=cognome, Email__c=email, Via__c=via, Cap__c=cap, Citta__c=citta,
                Provincia__c=provincia, Nazione__c=nazione, Telefono__c=telefono, Data_ricontatto__c=data_ricontatto, Fascia_oraria__c=fascia_oraria,
                Origine__c=origine, Sottocategoria_origine__c=sottocategoria_origine, Note__c=note, Richiesta_guida_cartacea__c=richiesta_guida_cartacea);
            insert nq;
            ConciliaDatiLead(); // ci provo subito...
            return 'OK';
        } catch (Exception ex){
            return ex.getMessage();
        }
    }
    
    static public void ConciliaDatiLead(){
        List<Lead> updated = new List<Lead>();
        List<LeadQueue__c> deleted = new List<LeadQueue__c>();
        // TODO: prevedere un "timeout" dei record o una cleanup periodica
        for(LeadQueue__c lq : [SELECT Nome__c, Cognome__c, Email__c, Via__c, Cap__c, Citta__c,
                Provincia__c, Nazione__c, Telefono__c, Data_ricontatto__c, Fascia_oraria__c,
                               Origine__c, Sottocategoria_origine__c, Note__c, Richiesta_guida_cartacea__c FROM LeadQueue__c]){
			List<Lead> leads = [Select Id from Lead where FirstName=:lq.Nome__c and LastName=:lq.Cognome__c and Email=:lq.Email__c];
            if(leads.size()<=0){
            	// Not found, will try later. Consider here if record is old enough to be deleted
            	continue;
            }
            Lead cl = leads.get(0);
            if(String.isNotBlank(lq.Via__c)) cl.Street = lq.Via__c;
            if(String.isNotBlank(lq.Cap__c))cl.PostalCode = lq.Cap__c;
            if(String.isNotBlank(lq.Citta__c))cl.City = lq.Citta__c;
            if(String.isNotBlank(lq.Provincia__c))cl.StateCode = lq.Provincia__c;
            if(String.isNotBlank(lq.Nazione__c))cl.CountryCode = lq.Nazione__c;
            if(String.isNotBlank(lq.Telefono__c))cl.Phone = lq.Telefono__c;
            if(lq.Data_ricontatto__c != null) cl.Data_ora_ricontatto__c = lq.Data_ricontatto__c;
            if(String.isNotBlank(lq.Fascia_oraria__c)) cl.Fascia_Oraria__c = lq.Fascia_oraria__c;
            if(String.isNotBlank(lq.Origine__c)) cl.Origine__c = lq.Origine__c;
            if(String.isNotBlank(lq.Sottocategoria_origine__c)) cl.Sottocategoria_origine__c = lq.Sottocategoria_origine__c;
            if(String.isNotBlank(lq.Note__c)) cl.Note__c = lq.Note__c;
            if(lq.Richiesta_guida_cartacea__c !=null) cl.Richiesta_guida__c = lq.Richiesta_guida_cartacea__c;
            updated.add(cl);
            deleted.add(lq);
        }
        update updated;
        delete deleted;
    }
}