Sorgente/src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Metodo_di_pagamento_kit__c</fullName>
        <label>Metodo di pagamento</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Bonifico</fullName>
                </value>
                <value>
                    <fullName>Carta di credito</fullName>
                </value>
                <value>
                    <fullName>PayPal</fullName>
                </value>
                <value>
                    <fullName>Giroconto postale</fullName>
                </value>
                <value>
                    <fullName>Contanti o assegno alla consegna</fullName>
                </value>
                <value>
                    <fullName>Contanti</fullName>
                </value>
                <value>
                    <fullName>Assegno</fullName>
                </value>
                <value>
                    <fullName>Bollettino postale</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Motivazione_Sconto__c</fullName>
        <label>Motivazione Sconto</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Già cliente</fullName>
                </value>
                <value>
                    <fullName>Programma amico</fullName>
                </value>
                <value>
                    <fullName>Medico</fullName>
                </value>
                <value>
                    <fullName>Dipendente</fullName>
                </value>
                <value>
                    <fullName>Adesione multipla</fullName>
                </value>
                <value>
                    <fullName>i-Contrazioni</fullName>
                </value>
                <value>
                    <fullName>Parente dipendente</fullName>
                </value>
                <value>
                    <fullName>Genoma</fullName>
                </value>
                <value>
                    <fullName>Cross selling</fullName>
                </value>
                <value>
                    <fullName>Fiera</fullName>
                </value>
                <value>
                    <fullName>Promozioni temporane</fullName>
                </value>
                <value>
                    <fullName>Altro</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Ripetizione_di__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Ripetizione di</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Opportunità ripetuta</relationshipLabel>
        <relationshipName>Opportunit</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

Sorgente/.apex/src/objects/Quote.object
<CustomObject>
    <fields>
        <fullName>Cliente_Professional__c</fullName>
        <label>Cliente Professional</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Cliente</fullName>
                </value>
                <value>
                    <fullName>Professional</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Maxi_rata__c</fullName>
        <label>Maxi rata</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Metodo_di_pagamento_kit__c</fullName>
        <label>Metodo di pagamento kit</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Bonifico</fullName>
                </value>
                <value>
                    <fullName>Carta di credito</fullName>
                </value>
                <value>
                    <fullName>Paypal</fullName>
                </value>
                <value>
                    <fullName>Giroconto postale</fullName>
                </value>
                <value>
                    <fullName>Contanti o assegno alla consegna</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Metodo_di_pagamento_servizio__c</fullName>
        <label>Metodo di pagamento servizio</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Bonifico</fullName>
                </value>
                <value>
                    <fullName>SDD</fullName>
                </value>
                <value>
                    <fullName>Giroconto</fullName>
                </value>
                <value>
                    <fullName>PayPal</fullName>
                </value>
                <value>
                    <fullName>Carta di credito</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Modalit_di_pagamento_servizio__c</fullName>
        <label>Modalità di pagamento servizio</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Unica soluzione</fullName>
                </value>
                <value>
                    <fullName>Dilazione pagamento</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Motivazione_sconto__c</fullName>
        <label>Motivazione sconto</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Già cliente</fullName>
                </value>
                <value>
                    <fullName>Programma amico</fullName>
                </value>
                <value>
                    <fullName>Medico</fullName>
                </value>
                <value>
                    <fullName>Dipendente</fullName>
                </value>
                <value>
                    <fullName>Adesione multipla</fullName>
                </value>
                <value>
                    <fullName>i-Contrazioni</fullName>
                </value>
                <value>
                    <fullName>Parente dipendente</fullName>
                </value>
                <value>
                    <fullName>Genoma</fullName>
                </value>
                <value>
                    <fullName>Cross selling</fullName>
                </value>
                <value>
                    <fullName>Fiera</fullName>
                </value>
                <value>
                    <fullName>Promozioni temporane</fullName>
                </value>
                <value>
                    <fullName>Altro</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Numero_rate__c</fullName>
        <label>Numero rate</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Salva_pagamento_senza_CF__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Salva pagamento senza CF</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Sorgente/.apex/src/objects/Ruolo_degli_Specialisti_Collaboratori__c.object
<CustomObject>
    <fields>
        <fullName>Opportunita__c</fullName>
        <label>Opportunità</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Ruoli degli Specialisti/Collaboratori</relationshipLabel>
        <relationshipName>Ruoli_degli_Specialisti_Collaboratori</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Referente__c</fullName>
        <label>Referente</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.RecordType.DeveloperName</field>
                <operation>equals</operation>
                <value>Specialista</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Ruoli degli Specialisti/Collaboratori</relationshipLabel>
        <relationshipName>Ruoli_degli_Specialisti_Collaboratori</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Ruolo__c</fullName>
        <label>Ruolo</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Specialista che consiglia</fullName>
                </value>
                <value>
                    <fullName>Specialista</fullName>
                </value>
                <value>
                    <fullName>Collaboratore che consiglia</fullName>
                </value>
                <value>
                    <fullName>Programma Amico</fullName>
                </value>
                <value>
                    <fullName>Operatore prelievo</fullName>
                </value>
                <value>
                    <fullName>Prescrittore</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Ruolo degli Specialisti/Collaboratori</label>
    <nameField>
        <displayFormat>A-{0000000}</displayFormat>
        <label>Nome Ruolo degli Specialisti/Collaborato</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Ruoli degli Specialisti/Collaboratori</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Sorgente/.apex/src/classes/CopyOpportunity.cls
public class CopyOpportunity {
    @InvocableMethod
    public static void CopyOpportunity(List<Opportunity> source){
        if(source == null || source.isEmpty()) return;
        Opportunity src = source.get(0);
        List<Opportunity> dests = [select ID from Opportunity where Ripetizione_di__c =: src.Id];
        if(dests.isEmpty()) {
            return;
        }
        // return;
        Opportunity dest = dests.get(0);
        
        /* RR */
        List<OpportunityContactRole> oppContacts = [Select ID, ContactId, OpportunityId, IsPrimary, IsDeleted, Role from OpportunityContactRole Where OpportunityId = :src.Id];

        List<OpportunityContactRole> opdests = oppcontacts.deepClone();
        for(OpportunityContactRole opdest : opdests){
            opdest.OpportunityId = dest.Id;
        }
        Insert(opdests);
        
        for(Ruolo_degli_Specialisti_Collaboratori__c rsrc : [select Id, Opportunita__c, Referente__c, Ruolo__c 
            from Ruolo_degli_Specialisti_Collaboratori__c where Opportunita__c = :src.Id]){
            Ruolo_degli_Specialisti_Collaboratori__c rdest = new Ruolo_degli_Specialisti_Collaboratori__c();
            rdest.Opportunita__c = dest.Id;
            rdest.Referente__c = rsrc.Referente__c;
            rdest.Ruolo__c = rsrc.Ruolo__c;
            Insert(rdest);
        }
        
        for(OpportunityLineItem isrc : [select Id, OpportunityId, PriceBookEntryId, 
            Quantity, TotalPrice, UnitPrice, ServiceDate, Description 
            from OpportunityLineItem where OpportunityId =:src.Id]){
            OpportunityLineItem idest = new OpportunityLineItem();
            idest.OpportunityId = src.Id;
            idest.PricebookEntryId = isrc.PricebookEntryId;
            idest.Quantity = isrc.Quantity;
            // idest.TotalPrice = isrc.TotalPrice;
            idest.UnitPrice = isrc.UnitPrice;
            idest.ServiceDate = isrc.ServiceDate;
            idest.Description = isrc.Description;
            Insert(idest);
        }
        // Clone quotes
       	List<Quote> srcQuotes = [Select Id, Name, OpportunityId, Pricebook2Id, ContactId, QuoteNumber, IsSyncing, ShippingHandling, Tax, Status, ExpirationDate, Description, Subtotal,
                                 TotalPrice, LineItemCount, BillingStreet,BillingCity,BillingState,BillingPostalCode,BillingCountry,ShippingStreet,ShippingCity,ShippingState,ShippingPostalCode,ShippingCountry,
                                 BillingName,ShippingName,Email,Phone,Fax,AccountId,Discount,GrandTotal,Motivazione_sconto__c, Metodo_di_pagamento_servizio__c, Modalit_di_pagamento_servizio__c,
                                 Metodo_di_pagamento_kit__c, Numero_rate__c, Maxi_rata__c, Cliente_Professional__c, Salva_Pagamento_senza_CF__c
                                 from Quote where OpportunityId = :src.Id];
        // List<Quote> destQuotes = srcQuotes.deepClone();
        
        for(Quote qsrc : srcQuotes){
            Quote qdest = qsrc.clone(false, true, false, false);
            qdest.OpportunityId = dest.Id;
            Insert(qdest);
            
            List<QuoteLineItem> srcQlis = [Select Id, LineNumber, QuoteId, PricebookEntryId, Quantity, UnitPrice, Discount, Description, 
                                       Product2Id, SortOrder, ListPrice, Subtotal, TotalPrice
                                       from QuoteLineItem where QuoteId =:qsrc.Id];
            
            List<QuoteLineItem> destQlis = srcQlis.deepClone();
            for(QuoteLineItem destQli :  destQlis){
                destQli.QuoteId = qdest.Id;
            }
            Insert(destQlis);
        }

        
    }
}