Sorgente/.apex/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Business_Unit__c</fullName>
        <label>Società</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>SS</fullName>
                </value>
                <value>
                    <fullName>SG</fullName>
                </value>
                <value>
                    <fullName>GS</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Costo_servizio_scelto__c</fullName>
        <description>Test SFDC</description>
        <label>Costo servizio scelto</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Data_Creazione_Anagrafica__c</fullName>
        <defaultValue>Today()</defaultValue>
        <label>Data Creazione Anagrafica</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Data_ordine__c</fullName>
        <label>Data ordine</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Ginecologo__c</fullName>
        <label>Ginecologo</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Origine__c</fullName>
        <label>Origine</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Amici/conoscenti</fullName>
                </value>
                <value>
                    <fullName>Corso Preparto</fullName>
                </value>
                <value>
                    <fullName>Siti e app satellite</fullName>
                </value>
                <value>
                    <fullName>Social media</fullName>
                </value>
                <value>
                    <fullName>Giornali/riviste</fullName>
                </value>
                <value>
                    <fullName>Fiere e Convegni</fullName>
                </value>
                <value>
                    <fullName>Specialista</fullName>
                </value>
                <value>
                    <fullName>KAM</fullName>
                </value>
                <value>
                    <fullName>Siti extra gruppo</fullName>
                </value>
                <value>
                    <fullName>Motore di ricerca</fullName>
                </value>
                <value>
                    <fullName>Pieghevole</fullName>
                </value>
                <value>
                    <fullName>Programma Amico</fullName>
                </value>
                <value>
                    <fullName>Collaboratore</fullName>
                </value>
                <value>
                    <fullName>Altro</fullName>
                </value>
                <value>
                    <fullName>Da verificare</fullName>
                </value>
                <value>
                    <fullName>Professional</fullName>
                </value>
                <value>
                    <fullName>Cross selling</fullName>
                </value>
                <value>
                    <fullName>Già cliente</fullName>
                </value>
                <value>
                    <fullName>Cross selling - Aurora</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Status_Prospect_cliente01__c</fullName>
        <label>Status Prospect/cliente</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

Sorgente/src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Origine__c</fullName>
        <label>Origine</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Amici/conoscenti</fullName>
                </value>
                <value>
                    <fullName>Corso Preparto</fullName>
                </value>
                <value>
                    <fullName>Siti e app satellite</fullName>
                </value>
                <value>
                    <fullName>Social media</fullName>
                </value>
                <value>
                    <fullName>Fiere e Convegni</fullName>
                </value>
                <value>
                    <fullName>Specialista</fullName>
                </value>
                <value>
                    <fullName>Professional</fullName>
                </value>
                <value>
                    <fullName>KAM</fullName>
                </value>
                <value>
                    <fullName>Siti extra gruppo</fullName>
                </value>
                <value>
                    <fullName>Motore di ricerca</fullName>
                </value>
                <value>
                    <fullName>Pieghevole</fullName>
                </value>
                <value>
                    <fullName>Collaboratore</fullName>
                </value>
                <value>
                    <fullName>Altro</fullName>
                </value>
                <value>
                    <fullName>Da verificare</fullName>
                </value>
                <value>
                    <fullName>Candidatura spontanea</fullName>
                </value>
                <value>
                    <fullName>Società di selezione</fullName>
                </value>
                <value>
                    <fullName>Istituto di formazione</fullName>
                </value>
                <value>
                    <fullName>Campagna interna</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>PC_SS__c</fullName>
        <label>PC-SS</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <recordTypes>
        <fullName>Collaboratore</fullName>
        <active>true</active>
        <description>Un collaboratore di Sorgente o Sorgente Genetica</description>
        <label>Collaboratore</label>
    </recordTypes>
    <recordTypes>
        <fullName>Specialista</fullName>
        <active>true</active>
        <description>Uno medico con caratteristiche da influencer</description>
        <label>Specialista</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

Sorgente/src/objects/Elenco_Pazienti__c.object
<CustomObject>
    <fields>
        <fullName>Ginecologo__c</fullName>
        <label>Ginecologo</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Elenco Pazienti</relationshipLabel>
        <relationshipName>Elenco_Pazienti</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Opportunita__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunità</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Elenco Pazienti</relationshipLabel>
        <relationshipName>Elenco_Pazienti</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Origine__c</fullName>
        <formula>TEXT( Opportunita__r.Origine__c )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Origine</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Punti_Consiglio__c</fullName>
        <label>Punti Consiglio</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Stato_Paziente__c</fullName>
        <label>Stato Paziente</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Da gestire</fullName>
                </value>
                <value>
                    <fullName>Gestito</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Elenco Pazienti</label>
    <nameField>
        <displayFormat>P-{000000}</displayFormat>
        <label>Numero Paziente</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Elenco Pazienti</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Sorgente/src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Agente_titolare_ginecologo__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Agente titolare ginecologo</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Business_Unit__c</fullName>
        <label>Business Unit</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>SS</fullName>
                </value>
                <value>
                    <fullName>SG</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Data_ordine__c</fullName>
        <label>Data ordine</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Ginecologo__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Ginecologo</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.RecordTypeId</field>
                <operation>equals</operation>
                <value>Specialista</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Opportunità (Ginecologo)</relationshipLabel>
        <relationshipName>Opportunit2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Notifica_ordine_kit_ctr_agente__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Notifica ordine kit/ctr agente</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Origine__c</fullName>
        <label>Origine</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Altro</fullName>
                </value>
                <value>
                    <fullName>Amici/conoscenti</fullName>
                </value>
                <value>
                    <fullName>Collaboratore</fullName>
                </value>
                <value>
                    <fullName>Corso Preparto</fullName>
                </value>
                <value>
                    <fullName>Cross selling</fullName>
                </value>
                <value>
                    <fullName>Cross selling - Aurora</fullName>
                </value>
                <value>
                    <fullName>Da verificare</fullName>
                </value>
                <value>
                    <fullName>Fiera</fullName>
                    <label>Fiere e Convegni</label>
                </value>
                <value>
                    <fullName>Già cliente</fullName>
                </value>
                <value>
                    <fullName>Giornali/riviste</fullName>
                </value>
                <value>
                    <fullName>KAM</fullName>
                </value>
                <value>
                    <fullName>Motore di ricerca</fullName>
                </value>
                <value>
                    <fullName>Pieghevole</fullName>
                </value>
                <value>
                    <fullName>Professional</fullName>
                </value>
                <value>
                    <fullName>Programma Amico</fullName>
                </value>
                <value>
                    <fullName>Siti e app satellite</fullName>
                </value>
                <value>
                    <fullName>Siti extra gruppo</fullName>
                </value>
                <value>
                    <fullName>Social media</fullName>
                </value>
                <value>
                    <fullName>Specialista</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Punti_Consiglio__c</fullName>
        <formula>Ginecologo__r.PC_SS__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Punti Consiglio</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Responsabile_prevendita__c</fullName>
        <label>Responsabile prevendita</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Stato_fatturazione__c</fullName>
        <defaultValue>&apos;Italia&apos;</defaultValue>
        <label>Nazione fatturazione</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Stato_spedizione__c</fullName>
        <defaultValue>&apos;Italia&apos;</defaultValue>
        <label>Nazione</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <recordTypes>
        <fullName>SS</fullName>
        <active>true</active>
        <businessProcess>SS</businessProcess>
        <label>SS</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

Sorgente/src/classes/TestRighePazientiGinecologo.cls
@isTest
public class TestRighePazientiGinecologo
{ 
    public static testmethod void test()
    {
      Account acc = new Account();
      acc.LastName = 'Test Paziente';
      acc.Business_Unit__c = 'Telefono';
      acc.Type = 'GS';
      acc.Ginecologo__c = 'Ginecologo';
      acc.Origine__c = 'Collaboratore';
      acc.Costo_servizio_scelto__c = 1.896;
      acc.Data_ordine__c = date.parse('09/05/2018');
      acc.Status_Prospect_cliente01__c = 'Chiuso perso';
      acc.BillingCountry = 'Italia';
      acc.ShippingCountry = 'Italia';
      acc.PersonMailingCountry = 'Italia';
      acc.PersonOtherCountry = 'Italia';
      acc.Data_Creazione_Anagrafica__c = Date.parse('02/05/2018');
      acc.RecordTypeId= Schema.SObjectType.Account.getRecordTypeInfosByName().get('Prospect/cliente').getRecordTypeId();
         
      insert acc;
      
      Contact con = new Contact();
      con.PC_SS__c = 10;
      con.LastName = 'Ginecologo';
      con.RecordTypeId = Schema.SObjectType.Contact.getRecordTypeInfosByName().get('Specialista').getRecordTypeId();
         
      insert con;
             
      Opportunity opp = new Opportunity();
      opp.Name = 'Opp test';
      opp.StageName = 'In firma';
      opp.Data_ordine__c = date.parse('09/05/2018');
      opp.CloseDate = date.parse('10/05/2018');
      opp.AccountId = acc.Id;
      opp.Ginecologo__c = con.Id;
      opp.Origine__c = 'Collaboratore';
      opp.Agente_titolare_ginecologo__c = Userinfo.getUserId();
      opp.Responsabile_prevendita__c = 'CIAO';
      opp.Stato_fatturazione__c = 'Italia';
      opp.Stato_spedizione__c = 'Italia';
      opp.Notifica_ordine_kit_ctr_agente__c = true;
      opp.RecordTypeId = Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get('SS').getRecordTypeId();
         
      insert opp;
        
      Opportunity opp1 = new Opportunity();
      opp1.Name = 'Opp1 test';
      opp1.StageName = 'In attesa parto';
      opp1.Data_ordine__c = date.parse('09/05/2018');
      opp1.CloseDate = date.parse('10/05/2018');
      opp1.AccountId = acc.Id;
      opp1.Ginecologo__c = con.Id;
      opp1.Origine__c = 'Collaboratore';
      opp1.Agente_titolare_ginecologo__c = Userinfo.getUserId();
      opp1.Responsabile_prevendita__c = 'CIAO';
      opp1.Stato_fatturazione__c = 'Italia';
      opp1.Stato_spedizione__c = 'Italia';
      opp1.Notifica_ordine_kit_ctr_agente__c = true;
      opp1.RecordTypeId = Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get('SS').getRecordTypeId();
         
      insert opp1;
      
      Opportunity opp2 = new Opportunity();
      opp2.Name = 'Opp test';
      opp2.StageName = 'Chiuso perso';
      opp2.Data_ordine__c = date.parse('09/05/2018');
      opp2.CloseDate = date.parse('10/05/2018');
      opp2.AccountId = acc.Id;
      opp2.Ginecologo__c = con.Id;
      opp2.Origine__c = 'Collaboratore';
      opp2.Agente_titolare_ginecologo__c = Userinfo.getUserId();
      opp2.Responsabile_prevendita__c = 'CIAO';
      opp2.Stato_fatturazione__c = 'Italia';
      opp2.Stato_spedizione__c = 'Italia';
      opp2.Notifica_ordine_kit_ctr_agente__c = true;
      opp2.RecordTypeId = Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get('SS').getRecordTypeId();
         
      insert opp2;
      opp.StageName = 'Preparto';
      update opp;
      Elenco_Pazienti__c e = [SELECT id, Opportunita__c, Ginecologo__c, Stato_Paziente__c, Punti_Consiglio__c
                              FROM Elenco_Pazienti__c
                              WHERE Opportunita__c =: opp.Id];
      e.Stato_Paziente__c = 'Gestito';
      update e;
     
      //Questa è per crearla negativa
      opp.StageName = 'Chiuso perso';
      update opp;
 
      //Questa è per cancellare opp1     
      opp1.StageName = 'Chiuso perso';
      update opp1;
     
      
 
}
}