Sorgente/.apex/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Ginecologo__c</fullName>
        <label>Ginecologo</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <recordTypes>
        <fullName>Professional</fullName>
        <active>true</active>
        <label>Professional</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

Sorgente/src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>PC_SS__c</fullName>
        <label>PC-SS</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <recordTypes>
        <fullName>Specialista</fullName>
        <active>true</active>
        <description>Uno medico con caratteristiche da influencer</description>
        <label>Specialista</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

Sorgente/src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Agente_titolare_ginecologo__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Agente titolare ginecologo</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Data_ora_prelievo_effettiva__c</fullName>
        <label>Data/ora prelievo effettiva</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Ginecologo__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Ginecologo</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.RecordTypeId</field>
                <operation>equals</operation>
                <value>Specialista</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Opportunità (Ginecologo)</relationshipLabel>
        <relationshipName>Opportunit2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Operatore_prelievo__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Operatore prelievo</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.Categoria_collaboratore__c</field>
                <operation>equals</operation>
                <value>Operatore prelievo</value>
            </filterItems>
            <filterItems>
                <field>$Source.Provincia_spedizione__c</field>
                <operation>equals</operation>
                <valueField>Contact.MailingState</valueField>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Prelievi effettuati</relationshipLabel>
        <relationshipName>Opportunit</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

Sorgente/.apex/src/classes/TestOppTriggers.cls
@isTest
public class TestOppTriggers {

    private static testMethod void testOppTriggersInsert(){
        Account a = new Account();
        a.FirstName = 'Unit';
        a.LastName = 'Test User';
        a.PersonEmail = 'sf_debug@bemerconsulting.com';
        a.RecordTypeId = AppSetup.recordTypePersonAccount;
        insert(a);
        
        Account p = new Account();
        p.Name = 'Unit Test Professional';
        p.RecordTypeId = AppSetup.recordTypeProfessional;
        insert(p);
        
        Contact s = new Contact();
        s.AccountId = p.Id;
        s.FirstName = 'Unit';
        s.LastName = 'Test Specialista';
        s.RecordTypeId = AppSetup.recordTypeSpecialista;
        insert(s);

        Contact con = new Contact();
        con.PC_SS__c = 10;
        con.LastName = 'Ginecologo';
        con.RecordTypeId = Schema.SObjectType.Contact.getRecordTypeInfosByName().get('Specialista').getRecordTypeId();
        List<User> u = [SELECT Id FROM User WHERE (IsActive = true)];
        if (u.size() > 0)
            con.OwnerId = u[0].Id;
        insert con;

        DateTime now = DateTime.now();
        Opportunity o1 = new Opportunity();
        o1.RecordTypeId = AppSetup.recordTypeSG;
        o1.Name = 'Opportunita Unit Test';
        o1.AccountId = a.Id;
        o1.StageName = 'Aperto';
        o1.CloseDate = Date.today();
        o1.Data_ora_prelievo_effettiva__c = now.addMonths(-1);
        o1.Operatore_prelievo__c = s.Id;
        o1.Ginecologo__c = con.Id;
        o1.Agente_titolare_ginecologo__c = con.OwnerId;
        insert(o1);
    }
}