Sorgente/.apex/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Agente__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Agente</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>User.Profile.Name</field>
                <operation>equals</operation>
                <value>Force.com - App Subscription User (KAM)</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>User</referenceTo>
        <relationshipName>Account</relationshipName>
        <type>Lookup</type>
    </fields>
    <recordTypes>
        <fullName>Professional</fullName>
        <active>true</active>
        <label>Professional</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

Sorgente/src/objects/Contact.object
<CustomObject>
    <recordTypes>
        <fullName>Specialista</fullName>
        <active>true</active>
        <description>Uno medico con caratteristiche da influencer</description>
        <label>Specialista</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

Sorgente/src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Agente__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Agente</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>User.Profile.Name</field>
                <operation>equals</operation>
                <value>Force.com - App Subscription User (KAM)</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>User</referenceTo>
        <relationshipName>Opportunit</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Metodo_di_pagamento_kit__c</fullName>
        <label>Metodo di pagamento</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Bonifico</fullName>
                </value>
                <value>
                    <fullName>Carta di credito</fullName>
                </value>
                <value>
                    <fullName>PayPal</fullName>
                </value>
                <value>
                    <fullName>Giroconto postale</fullName>
                </value>
                <value>
                    <fullName>Contanti o assegno alla consegna</fullName>
                </value>
                <value>
                    <fullName>Contanti</fullName>
                </value>
                <value>
                    <fullName>Assegno</fullName>
                </value>
                <value>
                    <fullName>Bollettino postale</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Motivazione_Sconto__c</fullName>
        <label>Motivazione Sconto</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Già cliente</fullName>
                </value>
                <value>
                    <fullName>Programma amico</fullName>
                </value>
                <value>
                    <fullName>Medico</fullName>
                </value>
                <value>
                    <fullName>Dipendente</fullName>
                </value>
                <value>
                    <fullName>Adesione multipla</fullName>
                </value>
                <value>
                    <fullName>i-Contrazioni</fullName>
                </value>
                <value>
                    <fullName>Parente dipendente</fullName>
                </value>
                <value>
                    <fullName>Genoma</fullName>
                </value>
                <value>
                    <fullName>Cross selling</fullName>
                </value>
                <value>
                    <fullName>Fiera</fullName>
                </value>
                <value>
                    <fullName>Promozioni temporane</fullName>
                </value>
                <value>
                    <fullName>Altro</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Ripetizione_di__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Ripetizione di</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Opportunità ripetuta</relationshipLabel>
        <relationshipName>Opportunit</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Via_fatturazione__c</fullName>
        <label>Via fatturazione</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

Sorgente/src/objects/Product2.object
<CustomObject>
    <recordTypes>
        <fullName>Prodotto</fullName>
        <active>true</active>
        <label>Prodotto</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Sorgente/.apex/src/objects/Quote.object
<CustomObject>
    <fields>
        <fullName>Cliente_Professional__c</fullName>
        <label>Cliente Professional</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Cliente</fullName>
                </value>
                <value>
                    <fullName>Professional</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Maxi_rata__c</fullName>
        <label>Maxi rata</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Metodo_di_pagamento_kit__c</fullName>
        <label>Metodo di pagamento kit</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Bonifico</fullName>
                </value>
                <value>
                    <fullName>Carta di credito</fullName>
                </value>
                <value>
                    <fullName>Paypal</fullName>
                </value>
                <value>
                    <fullName>Giroconto postale</fullName>
                </value>
                <value>
                    <fullName>Contanti o assegno alla consegna</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Metodo_di_pagamento_servizio__c</fullName>
        <label>Metodo di pagamento servizio</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Bonifico</fullName>
                </value>
                <value>
                    <fullName>SDD</fullName>
                </value>
                <value>
                    <fullName>Giroconto</fullName>
                </value>
                <value>
                    <fullName>PayPal</fullName>
                </value>
                <value>
                    <fullName>Carta di credito</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Modalit_di_pagamento_servizio__c</fullName>
        <label>Modalità di pagamento servizio</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Unica soluzione</fullName>
                </value>
                <value>
                    <fullName>Dilazione pagamento</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Motivazione_sconto__c</fullName>
        <label>Motivazione sconto</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Già cliente</fullName>
                </value>
                <value>
                    <fullName>Programma amico</fullName>
                </value>
                <value>
                    <fullName>Medico</fullName>
                </value>
                <value>
                    <fullName>Dipendente</fullName>
                </value>
                <value>
                    <fullName>Adesione multipla</fullName>
                </value>
                <value>
                    <fullName>i-Contrazioni</fullName>
                </value>
                <value>
                    <fullName>Parente dipendente</fullName>
                </value>
                <value>
                    <fullName>Genoma</fullName>
                </value>
                <value>
                    <fullName>Cross selling</fullName>
                </value>
                <value>
                    <fullName>Fiera</fullName>
                </value>
                <value>
                    <fullName>Promozioni temporane</fullName>
                </value>
                <value>
                    <fullName>Altro</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Numero_rate__c</fullName>
        <label>Numero rate</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Salva_pagamento_senza_CF__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Salva pagamento senza CF</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Sorgente/.apex/src/objects/Ruolo_degli_Specialisti_Collaboratori__c.object
<CustomObject>
    <fields>
        <fullName>Opportunita__c</fullName>
        <label>Opportunità</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Ruoli degli Specialisti/Collaboratori</relationshipLabel>
        <relationshipName>Ruoli_degli_Specialisti_Collaboratori</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Referente__c</fullName>
        <label>Referente</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.RecordType.DeveloperName</field>
                <operation>equals</operation>
                <value>Specialista</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Ruoli degli Specialisti/Collaboratori</relationshipLabel>
        <relationshipName>Ruoli_degli_Specialisti_Collaboratori</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Ruolo__c</fullName>
        <label>Ruolo</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Specialista che consiglia</fullName>
                </value>
                <value>
                    <fullName>Specialista</fullName>
                </value>
                <value>
                    <fullName>Collaboratore che consiglia</fullName>
                </value>
                <value>
                    <fullName>Programma Amico</fullName>
                </value>
                <value>
                    <fullName>Operatore prelievo</fullName>
                </value>
                <value>
                    <fullName>Prescrittore</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Ruolo degli Specialisti/Collaboratori</label>
    <nameField>
        <displayFormat>A-{0000000}</displayFormat>
        <label>Nome Ruolo degli Specialisti/Collaborato</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Ruoli degli Specialisti/Collaboratori</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Sorgente/src/classes/TestCopyOpportunity.cls
@isTest
public class TestCopyOpportunity {
    private static testMethod void testCopy(){
        Test.startTest();
        // empty list
        List<Opportunity> opps = new List<Opportunity>();
        CopyOpportunity.CopyOpportunity(opps);
        
        Account a = new Account();
        a.FirstName = 'Unit';
        a.LastName = 'Test User';
        a.PersonEmail = 'ssineriz@gmail.com';
        a.RecordTypeId = AppSetup.recordTypePersonAccount;
        a.Agente__c = [select Id from User where Name='TestKam'].get(0).Id;
        insert(a);

        Account p = new Account();
        p.Name = 'Unit Test Professional';
        p.RecordTypeId = AppSetup.recordTypeProfessional;
        insert(p);
        
        Contact s = new Contact();
        s.AccountId = p.Id;
        s.FirstName = 'Unit';
        s.LastName = 'Test Specialista';
        s.RecordTypeId = AppSetup.recordTypeSpecialista;   
        insert(s);
        
        Product2 prod = new Product2();
        prod.Name = 'Unit Test Prodotto';
        prod.RecordTypeId = AppSetup.recordTypeServizi;
        insert prod;
        
        PricebookEntry pbe = new PricebookEntry();
        pbe.Pricebook2Id = Test.getStandardPricebookId();
        pbe.UnitPrice = 10;
        pbe.IsActive = true;
        pbe.Product2Id = prod.Id;
        insert(pbe);
        
        Opportunity o = new Opportunity();
        o.RecordTypeId = AppSetup.recordTypeSS;
        o.Name = 'Opportunita Unit Test';
        o.AccountId = a.Id;
        o.StageName = 'Aperto';
        o.CloseDate = Date.today();
        
        o.Via_fatturazione__c = 'Via col vento';
        insert(o);
		
        opps.add(o);
        // copy doesn't exist
        CopyOpportunity.CopyOpportunity(opps);
        
        // test allinea indirizzi
        o.Via_fatturazione__c = 'Via le mani dal naso';
        update(o);
        
        Opportunity d = o.clone(false, true, false, false);
        d.Ripetizione_di__c = o.Id;
        insert(d);
        
        // ContactId, OpportunityId, IsPrimary, IsDeleted, Role
        OpportunityContactRole ocr = new OpportunityContactRole();
        ocr.OpportunityId = o.Id;
        ocr.Role = 'Madre';
        ocr.ContactId = [Select Id from Contact where AccountId =: a.Id].get(0).Id;
        ocr.IsPrimary = true;
        insert(ocr);
        
        // Opportunita__c, Referente__c, Ruolo__c 
		Ruolo_degli_Specialisti_Collaboratori__c rsc = new Ruolo_degli_Specialisti_Collaboratori__c();
        rsc.Opportunita__c = o.Id;
        rsc.Referente__c = s.Id;
        rsc.Ruolo__c = 'Specialista';
        insert(rsc);
        
        // OpportunityId, PriceBookEntryId, Quantity, TotalPrice, UnitPrice, ServiceDate, Description
        OpportunityLineItem oli = new OpportunityLineItem();
        oli.OpportunityId = o.Id;
        oli.PricebookEntryId = pbe.Id;
        oli.Quantity = 2;
        oli.TotalPrice = 25;
        Insert(oli);
        
        // Name, OpportunityId, Pricebook2Id, ContactId, QuoteNumber, IsSyncing, ShippingHandling, Tax, Status, ExpirationDate, Description, Subtotal,
        // TotalPrice, LineItemCount, BillingStreet,BillingCity,BillingState,BillingPostalCode,BillingCountry,ShippingStreet,ShippingCity,ShippingState,ShippingPostalCode,ShippingCountry,
        // BillingName,ShippingName,Email,Phone,Fax,AccountId,Discount,GrandTotal,Motivazione_sconto__c, Metodo_di_pagamento_servizio__c, Modalit_di_pagamento_servizio__c,
        // Metodo_di_pagamento_kit__c, Numero_rate__c, Maxi_rata__c, Cliente_Professional__c, Salva_Pagamento_senza_CF__c
        Quote qu = new Quote();
        qu.Name='Unit Test Quote';
        qu.OpportunityId = o.Id;
        qu.Pricebook2Id = Test.getStandardPricebookId();
        insert(qu);
        
        // LineNumber, QuoteId, PricebookEntryId, Quantity, UnitPrice, Discount, Description, Product2Id, SortOrder, ListPrice, Subtotal, TotalPrice
        QuoteLineItem qli = new QuoteLineItem();
        qli.QuoteId = qu.Id;
        qli.PricebookEntryId = pbe.Id;
        qli.Quantity = 2;
        qli.UnitPrice = 17;
        insert(qli);
        
        CopyOpportunity.CopyOpportunity(opps);
		Test.stopTest();
    }
}