Sorgente/.apex/src/objects/Account.object
<CustomObject>
    <recordTypes>
        <fullName>Professional</fullName>
        <active>true</active>
        <label>Professional</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

Sorgente/src/objects/Contact.object
<CustomObject>
    <recordTypes>
        <fullName>Specialista</fullName>
        <active>true</active>
        <description>Uno medico con caratteristiche da influencer</description>
        <label>Specialista</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

Sorgente/src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Data_ora_prelievo_effettiva__c</fullName>
        <label>Data/ora prelievo effettiva</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Operatore_prelievo__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Operatore prelievo</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.Categoria_collaboratore__c</field>
                <operation>equals</operation>
                <value>Operatore prelievo</value>
            </filterItems>
            <filterItems>
                <field>$Source.Provincia_spedizione__c</field>
                <operation>equals</operation>
                <valueField>Contact.MailingState</valueField>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Prelievi effettuati</relationshipLabel>
        <relationshipName>Opportunit</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

Sorgente/.apex/src/objects/Ruolo_degli_Specialisti_Collaboratori__c.object
<CustomObject>
    <fields>
        <fullName>Opportunita__c</fullName>
        <label>Opportunità</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Ruoli degli Specialisti/Collaboratori</relationshipLabel>
        <relationshipName>Ruoli_degli_Specialisti_Collaboratori</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Referente__c</fullName>
        <label>Referente</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.RecordType.DeveloperName</field>
                <operation>equals</operation>
                <value>Specialista</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Ruoli degli Specialisti/Collaboratori</relationshipLabel>
        <relationshipName>Ruoli_degli_Specialisti_Collaboratori</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Ruolo__c</fullName>
        <label>Ruolo</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Specialista che consiglia</fullName>
                </value>
                <value>
                    <fullName>Specialista</fullName>
                </value>
                <value>
                    <fullName>Collaboratore che consiglia</fullName>
                </value>
                <value>
                    <fullName>Programma Amico</fullName>
                </value>
                <value>
                    <fullName>Operatore prelievo</fullName>
                </value>
                <value>
                    <fullName>Prescrittore</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Ruolo degli Specialisti/Collaboratori</label>
    <nameField>
        <displayFormat>A-{0000000}</displayFormat>
        <label>Nome Ruolo degli Specialisti/Collaborato</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Ruoli degli Specialisti/Collaboratori</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Sorgente/.apex/src/classes/TestCalcoloPrelievi.cls
@isTest
public class TestCalcoloPrelievi {
    private static testMethod void testCalcoloPrelievi(){
        Account a = new Account();
        a.FirstName = 'Unit';
        a.LastName = 'Test User';
        a.PersonEmail = 'ssineriz@gmail.com';
        a.RecordTypeId = AppSetup.recordTypePersonAccount;
        insert(a);
        
        Account p = new Account();
        p.Name = 'Unit Test Professional';
        p.RecordTypeId = AppSetup.recordTypeProfessional;
        insert(p);
        
        Contact s = new Contact();
        s.AccountId = p.Id;
        s.FirstName = 'Unit';
        s.LastName = 'Test Specialista';
        s.RecordTypeId = AppSetup.recordTypeSpecialista;      
        insert(s);
        
        DateTime now = DateTime.now();
        Opportunity o1 = new Opportunity();
        o1.RecordTypeId = AppSetup.recordTypeSG;
        o1.Name = 'Opportunita Unit Test';
        o1.AccountId = a.Id;
        o1.StageName = 'Aperto';
        o1.CloseDate = Date.today();
        o1.Data_ora_prelievo_effettiva__c = now.addMonths(-1);
        o1.Operatore_prelievo__c = s.Id;
        insert(o1);
        
        /*
        Ruolo_degli_Specialisti_Collaboratori__c rs = new Ruolo_degli_Specialisti_Collaboratori__c();
        rs.Referente__c = s.Id;
        rs.Ruolo__c = 'Operatore prelievo';
        rs.Opportunita__c = o1.Id;
        insert(rs);
        */
        new CalcoloPrelievi().execute();
    }
}