Sorgente/.apex/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Agente__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Agente</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>User.Profile.Name</field>
                <operation>equals</operation>
                <value>Force.com - App Subscription User (KAM)</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>User</referenceTo>
        <relationshipName>Account</relationshipName>
        <type>Lookup</type>
    </fields>
    <recordTypes>
        <fullName>Professional</fullName>
        <active>true</active>
        <label>Professional</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

Sorgente/src/objects/Contact.object
<CustomObject>
    <recordTypes>
        <fullName>Specialista</fullName>
        <active>true</active>
        <description>Uno medico con caratteristiche da influencer</description>
        <label>Specialista</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

Sorgente/.apex/src/objects/LeadQueue__c.object
<CustomObject>
    <fields>
        <fullName>Cognome__c</fullName>
        <label>Cognome</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Nome__c</fullName>
        <label>Nome</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <label>LeadQueue</label>
    <nameField>
        <displayFormat>LQ-{000000000}</displayFormat>
        <label>Nome LeadQueue</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>LeadQueue</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Sorgente/src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>AWB_verso_lab__c</fullName>
        <label>AWB verso lab</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Agente__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Agente</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>User.Profile.Name</field>
                <operation>equals</operation>
                <value>Force.com - App Subscription User (KAM)</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>User</referenceTo>
        <relationshipName>Opportunit</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Data_di_desiderata_ricezione__c</fullName>
        <label>Data di ricezione kit</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Data_di_spedizione_desiderata__c</fullName>
        <label>Data di spedizione kit</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Data_spedizione_kit_da_decidere__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Data spedizione kit da decidere</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Metodo_di_pagamento_kit__c</fullName>
        <label>Metodo di pagamento</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Bonifico</fullName>
                </value>
                <value>
                    <fullName>Carta di credito</fullName>
                </value>
                <value>
                    <fullName>PayPal</fullName>
                </value>
                <value>
                    <fullName>Giroconto postale</fullName>
                </value>
                <value>
                    <fullName>Contanti o assegno alla consegna</fullName>
                </value>
                <value>
                    <fullName>Contanti</fullName>
                </value>
                <value>
                    <fullName>Assegno</fullName>
                </value>
                <value>
                    <fullName>Bollettino postale</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Motivazione_Sconto__c</fullName>
        <label>Motivazione Sconto</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Già cliente</fullName>
                </value>
                <value>
                    <fullName>Programma amico</fullName>
                </value>
                <value>
                    <fullName>Medico</fullName>
                </value>
                <value>
                    <fullName>Dipendente</fullName>
                </value>
                <value>
                    <fullName>Adesione multipla</fullName>
                </value>
                <value>
                    <fullName>i-Contrazioni</fullName>
                </value>
                <value>
                    <fullName>Parente dipendente</fullName>
                </value>
                <value>
                    <fullName>Genoma</fullName>
                </value>
                <value>
                    <fullName>Cross selling</fullName>
                </value>
                <value>
                    <fullName>Fiera</fullName>
                </value>
                <value>
                    <fullName>Promozioni temporane</fullName>
                </value>
                <value>
                    <fullName>Altro</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Ripetizione_di__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Ripetizione di</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Opportunità ripetuta</relationshipLabel>
        <relationshipName>Opportunit</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

Sorgente/src/objects/Product2.object
<CustomObject>
    <recordTypes>
        <fullName>Prodotto</fullName>
        <active>true</active>
        <label>Prodotto</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Sorgente/.apex/src/objects/Quote.object
<CustomObject>
    <fields>
        <fullName>Cliente_Professional__c</fullName>
        <label>Cliente Professional</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Cliente</fullName>
                </value>
                <value>
                    <fullName>Professional</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Maxi_rata__c</fullName>
        <label>Maxi rata</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Metodo_di_pagamento_kit__c</fullName>
        <label>Metodo di pagamento kit</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Bonifico</fullName>
                </value>
                <value>
                    <fullName>Carta di credito</fullName>
                </value>
                <value>
                    <fullName>Paypal</fullName>
                </value>
                <value>
                    <fullName>Giroconto postale</fullName>
                </value>
                <value>
                    <fullName>Contanti o assegno alla consegna</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Metodo_di_pagamento_servizio__c</fullName>
        <label>Metodo di pagamento servizio</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Bonifico</fullName>
                </value>
                <value>
                    <fullName>SDD</fullName>
                </value>
                <value>
                    <fullName>Giroconto</fullName>
                </value>
                <value>
                    <fullName>PayPal</fullName>
                </value>
                <value>
                    <fullName>Carta di credito</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Modalit_di_pagamento_servizio__c</fullName>
        <label>Modalità di pagamento servizio</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Unica soluzione</fullName>
                </value>
                <value>
                    <fullName>Dilazione pagamento</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Motivazione_sconto__c</fullName>
        <label>Motivazione sconto</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Già cliente</fullName>
                </value>
                <value>
                    <fullName>Programma amico</fullName>
                </value>
                <value>
                    <fullName>Medico</fullName>
                </value>
                <value>
                    <fullName>Dipendente</fullName>
                </value>
                <value>
                    <fullName>Adesione multipla</fullName>
                </value>
                <value>
                    <fullName>i-Contrazioni</fullName>
                </value>
                <value>
                    <fullName>Parente dipendente</fullName>
                </value>
                <value>
                    <fullName>Genoma</fullName>
                </value>
                <value>
                    <fullName>Cross selling</fullName>
                </value>
                <value>
                    <fullName>Fiera</fullName>
                </value>
                <value>
                    <fullName>Promozioni temporane</fullName>
                </value>
                <value>
                    <fullName>Altro</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Numero_rate__c</fullName>
        <label>Numero rate</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Salva_pagamento_senza_CF__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Salva pagamento senza CF</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Sorgente/.apex/src/objects/Ruolo_degli_Specialisti_Collaboratori__c.object
<CustomObject>
    <fields>
        <fullName>Opportunita__c</fullName>
        <label>Opportunità</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Ruoli degli Specialisti/Collaboratori</relationshipLabel>
        <relationshipName>Ruoli_degli_Specialisti_Collaboratori</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Referente__c</fullName>
        <label>Referente</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.RecordType.DeveloperName</field>
                <operation>equals</operation>
                <value>Specialista</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Ruoli degli Specialisti/Collaboratori</relationshipLabel>
        <relationshipName>Ruoli_degli_Specialisti_Collaboratori</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Ruolo__c</fullName>
        <label>Ruolo</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Specialista che consiglia</fullName>
                </value>
                <value>
                    <fullName>Specialista</fullName>
                </value>
                <value>
                    <fullName>Collaboratore che consiglia</fullName>
                </value>
                <value>
                    <fullName>Programma Amico</fullName>
                </value>
                <value>
                    <fullName>Operatore prelievo</fullName>
                </value>
                <value>
                    <fullName>Prescrittore</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Ruolo degli Specialisti/Collaboratori</label>
    <nameField>
        <displayFormat>A-{0000000}</displayFormat>
        <label>Nome Ruolo degli Specialisti/Collaborato</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Ruoli degli Specialisti/Collaboratori</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Sorgente/.apex/src/classes/TestUtilities.cls
@IsTest
public class TestUtilities {
    private static testMethod void testUtilitiesCf(){ 
        Utilities.checkCodiceFiscale('AAAA');
        Utilities.checkCodiceFiscale('XXX,,,XXX___XXX___Z');
        Utilities.checkCodiceFiscale('SNRJQS72R17Z600Y');
        Utilities.checkCodiceFiscale('SNRJQS72R17Z600W');
    }
    
    public static testMethod void testSearchdupesController() {
        //PageReference pageRef = Page.Home;
        //Test.setCurrentPage(pageRef);
        ApexPages.currentPage().getParameters().put('name', 'pippo');
        ApexPages.currentPage().getParameters().put('firstname', 'pippo');
        ApexPages.currentPage().getParameters().put('lastname', 'pippo');
        ApexPages.currentPage().getParameters().put('id', '');
        SearchdupesController controller = new SearchdupesController();
    }
    
    public static testMethod void testAssegnaListinoEMergeOppController() {
        List<Opportunity> opps = new List<Opportunity>();
        AssegnaListino.AssegnaListino(opps);
        
        Account a = new Account();
        a.FirstName = 'Unit';
        a.LastName = 'Test User';
        a.PersonEmail = 'ssineriz@gmail.com';
        a.RecordTypeId = AppSetup.recordTypePersonAccount;
        a.Agente__c = [select Id from User where Name='TestKam'].get(0).Id;
        insert(a);

        Account p = new Account();
        p.Name = 'Unit Test Professional';
        p.RecordTypeId = AppSetup.recordTypeProfessional;
        insert(p);
        
        Contact s = new Contact();
        s.AccountId = p.Id;
        s.FirstName = 'Unit';
        s.LastName = 'Test Specialista';
        s.RecordTypeId = AppSetup.recordTypeSpecialista;   
        insert(s);
        
        Product2 prod = new Product2();
        prod.Name = 'Unit Test Prodotto';
        prod.RecordTypeId = AppSetup.recordTypeServizi;
        insert prod;
        
        PricebookEntry pbe = new PricebookEntry();
        pbe.Pricebook2Id = Test.getStandardPricebookId();
        pbe.UnitPrice = 10;
        pbe.IsActive = true;
        pbe.Product2Id = prod.Id;
        insert pbe;
        
        Opportunity o = new Opportunity();
        o.RecordTypeId = AppSetup.recordTypeSS;
        o.Name = 'Opportunita Unit Test';
        o.AccountId = a.Id;
        o.StageName = 'Aperto';
        o.CloseDate = Date.today();
        
        o.AWB_verso_lab__c = '9846408246';
        insert(o);
		new UpdateTrackingData().execute();
        
        opps.add(o);

        ApexPages.currentPage().getParameters().put('id', o.Id);
        MergeOpportunitiesController  moc = new MergeOpportunitiesController();
        moc.opp1Id = o.Id;
        // copy doesn't exist
        AssegnaListino.AssegnaListino(opps);
        
        Opportunity d = o.clone(false, true, false, false);
        d.Ripetizione_di__c = o.Id;
        insert(d);
        
        Opportunity md = o.clone(false, true, false, false);
        md.RecordTypeId = AppSetup.recordTypeSS;
        insert(md);
        moc.opp2Id = md.Id;
        
        md.Data_di_spedizione_desiderata__c = Date.today();
        md.Data_di_desiderata_ricezione__c = Date.today();
        md.Data_spedizione_kit_da_decidere__c = true;
        md.StageName = 'In firma';
        try{
        	update(md);
        } catch (Exception ex){
            System.Assert(ex.getMessage().contains('FIELD_CUSTOM_VALIDATION_EXCEPTION'));
        }

        moc.mergeOpportunities();
        
        // ContactId, OpportunityId, IsPrimary, IsDeleted, Role
        OpportunityContactRole ocr = new OpportunityContactRole();
        ocr.OpportunityId = o.Id;
        ocr.Role = 'Madre';
        ocr.ContactId = [Select Id from Contact where AccountId =: a.Id].get(0).Id;
        ocr.IsPrimary = true;
        insert(ocr);
        
        // Opportunita__c, Referente__c, Ruolo__c 
		Ruolo_degli_Specialisti_Collaboratori__c rsc = new Ruolo_degli_Specialisti_Collaboratori__c();
        rsc.Opportunita__c = o.Id;
        rsc.Referente__c = s.Id;
        rsc.Ruolo__c = 'Specialista';
        insert(rsc);
        
        // OpportunityId, PriceBookEntryId, Quantity, TotalPrice, UnitPrice, ServiceDate, Description
        OpportunityLineItem oli = new OpportunityLineItem();
        oli.OpportunityId = o.Id;
        oli.PricebookEntryId = pbe.Id;
        oli.Quantity = 2;
        oli.TotalPrice = 25;
        Insert(oli);
        
        // Name, OpportunityId, Pricebook2Id, ContactId, QuoteNumber, IsSyncing, ShippingHandling, Tax, Status, ExpirationDate, Description, Subtotal,
        // TotalPrice, LineItemCount, BillingStreet,BillingCity,BillingState,BillingPostalCode,BillingCountry,ShippingStreet,ShippingCity,ShippingState,ShippingPostalCode,ShippingCountry,
        // BillingName,ShippingName,Email,Phone,Fax,AccountId,Discount,GrandTotal,Motivazione_sconto__c, Metodo_di_pagamento_servizio__c, Modalit_di_pagamento_servizio__c,
        // Metodo_di_pagamento_kit__c, Numero_rate__c, Maxi_rata__c, Cliente_Professional__c, Salva_Pagamento_senza_CF__c
        Quote qu = new Quote();
        qu.Name='Unit Test Quote';
        qu.OpportunityId = o.Id;
        qu.Pricebook2Id = Test.getStandardPricebookId();
        insert(qu);
        
        // LineNumber, QuoteId, PricebookEntryId, Quantity, UnitPrice, Discount, Description, Product2Id, SortOrder, ListPrice, Subtotal, TotalPrice
        QuoteLineItem qli = new QuoteLineItem();
        qli.QuoteId = qu.Id;
        qli.PricebookEntryId = pbe.Id;
        qli.Quantity = 2;
        qli.UnitPrice = 17;
        insert(qli);
        
        AssegnaListino.AssegnaListino(opps);
    }
    
    public static testMethod void testGetPraticaWS() {
        
        PraticaWS.getUserByName('0014E00000MhYI6QAN');
        PraticaWS.getAccountByExternalId('0014E00000MhYI6QAN');
        PraticaWS.getAccountById('0014E00000MhYI6QAN');
        PraticaWS.getPersonAccountByExternalId('0014E00000MhYI6QAN');
        PraticaWS.getPersonAccountById('0014E00000MhYI6QAN');
        PraticaWS.getContactByIDReferente('0014E00000MhYI6QAN');
        PraticaWS.getGinecologi();
        PraticaWS.getGinecologoByCodiceUnivoco('0014E00000MhYI6QAN');
        PraticaWS.getOspedali();
        PraticaWS.getOspedaleByCodiceUnivoco('0014E00000MhYI6QAN');
        PraticaWS.getPersonAccountByName('Test');
        PraticaWS.getContactById('0014E00000MhYI6QAN');
        PraticaWS.getPersonAccountByName('Test');
        PraticaWS.getPraticaByCodiceOrdine('12345');
        PraticaWS.getPraticaByNumeroPratica('54321');
        PraticaWS.getPraticaByAccountId('0014E00000MhYI6QAN');
            
        Account a = new Account();
        a.FirstName = 'Unit';
        a.LastName = 'Test User';
        a.PersonEmail = 'ssineriz@gmail.com';
        a.RecordTypeId = AppSetup.recordTypePersonAccount;
        a.Agente__c = [select Id from User where Name='TestKam'].get(0).Id;
        insert(a);
        
    	PraticaWS.Pratica p = PraticaWS.getNuovaPratica();
        // [Name, StageName, CloseDate
        p.Opportunity.Name='TestOpp';
        p.Opportunity.StageName='Aperto';
        p.Opportunity.CloseDate= Date.today();
        p.Opportunity.AccountId = a.Id;
    	p = PraticaWS.updateOpportunity(p);
        p = PraticaWS.getPraticaById(p.Opportunity.Id);
        p = PraticaWS.updateGenitori(p);
    }
    
    public static testMethod void testReassign() {
        Lead l = new Lead(FirstName='New Lead', LastName='Lead New');
        insert(l);
        List<Id> leads = new List<Id>();
        leads.add(l.Id);
        ReassignAfterConversion.processRecords(leads);
    }

    public static testMethod void testStatics() {
        ButtonResetFlagGuida.Reset();
        LeadQueue__c lq = new LeadQueue__c(Nome__c = 'Harry', Cognome__c='Potter', Email__c='a@b.c');
        insert lq;
        Lead l = new Lead(FirstName='Harry', LastName='Potter', Email='a@b.c');
        insert(l);
        
    }    

    public static testMethod void testGeneticaWs() {
        GeneticaWS.getUserByName('Test');
        GeneticaWS.getAccountByExternalId('0014E00000MhYI6QAN');
        GeneticaWS.getAccountById('0014E00000MhYI6QAN');
        GeneticaWS.getNuoviOrdini();
        GeneticaWS.getNuovaGestioneCliente();
        GeneticaWS.getListinoByName('Listino');		
    }
}