Sorgente/.apex/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Punti_consiglio_totali_SG__c</fullName>
        <label>Punti consiglio totali SG</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Punti_consiglio_totali_SS__c</fullName>
        <label>Punti consiglio totali SS</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <recordTypes>
        <fullName>Professional</fullName>
        <active>true</active>
        <label>Professional</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

Sorgente/src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Punti_consiglio_totali_SG__c</fullName>
        <label>Punti consiglio totali SG</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Punti_consiglio_totali_SS__c</fullName>
        <label>Punti consiglio totali SS</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <recordTypes>
        <fullName>Specialista</fullName>
        <active>true</active>
        <description>Uno medico con caratteristiche da influencer</description>
        <label>Specialista</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

Sorgente/src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Ospedale_Punto_prelievo__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Ospedale/Punto prelievo</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Professional</value>
            </filterItems>
            <filterItems>
                <field>Account.Struttura_abilitata_ai_parti__c</field>
                <operation>equals</operation>
                <value>Si</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Opportunità (Ospedale/Punto prelievo)</relationshipLabel>
        <relationshipName>Opportunit1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Punti_Consiglio__c</fullName>
        <formula>Ginecologo__r.PC_SS__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Punti Consiglio</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <recordTypes>
        <fullName>SG</fullName>
        <active>true</active>
        <businessProcess>SG</businessProcess>
        <label>SG</label>
    </recordTypes>
    <recordTypes>
        <fullName>SS</fullName>
        <active>true</active>
        <businessProcess>SS</businessProcess>
        <label>SS</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

Sorgente/.apex/src/objects/Pricebook2.object
<CustomObject>
    <fields>
        <fullName>Punti_Consiglio_SS__c</fullName>
        <label>Punti Consiglio SS</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Tipo_Listino__c</fullName>
        <label>Tipo listino</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Punti consiglio</fullName>
                </value>
                <value>
                    <fullName>Acquisto</fullName>
                </value>
                <value>
                    <fullName>Libero</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ReadSelect</sharingModel>
</CustomObject>

Sorgente/src/objects/PricebookEntry.object
<CustomObject>
    <fields>
        <fullName>Punti_consiglio__c</fullName>
        <label>Punti consiglio</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
</CustomObject>

Sorgente/.apex/src/objects/Ruolo_degli_Specialisti_Collaboratori__c.object
<CustomObject>
    <fields>
        <fullName>Opportunita__c</fullName>
        <label>Opportunità</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Ruoli degli Specialisti/Collaboratori</relationshipLabel>
        <relationshipName>Ruoli_degli_Specialisti_Collaboratori</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Referente__c</fullName>
        <label>Referente</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.RecordType.DeveloperName</field>
                <operation>equals</operation>
                <value>Specialista</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Ruoli degli Specialisti/Collaboratori</relationshipLabel>
        <relationshipName>Ruoli_degli_Specialisti_Collaboratori</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Ruolo__c</fullName>
        <label>Ruolo</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Specialista che consiglia</fullName>
                </value>
                <value>
                    <fullName>Specialista</fullName>
                </value>
                <value>
                    <fullName>Collaboratore che consiglia</fullName>
                </value>
                <value>
                    <fullName>Programma Amico</fullName>
                </value>
                <value>
                    <fullName>Operatore prelievo</fullName>
                </value>
                <value>
                    <fullName>Prescrittore</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Ruolo degli Specialisti/Collaboratori</label>
    <nameField>
        <displayFormat>A-{0000000}</displayFormat>
        <label>Nome Ruolo degli Specialisti/Collaborato</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Ruoli degli Specialisti/Collaboratori</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Sorgente/src/classes/AssegnaPuntiConsiglio.cls
public class AssegnaPuntiConsiglio {
	@InvocableMethod
    public static void AssegnaPuntiConsiglio(List<Opportunity> source){
    	// valido per SS e SG
    	if(source == null || source.size() <=0){
            return;
        }
        
        Opportunity opp = source.get(0);
        if(opp.Pricebook2Id == null){
            return;
        }
        Double punti = 0;
		List<PriceBook2> pbl = [select Punti_Consiglio_SS__c, Tipo_Listino__c FROM PriceBook2 where Id = :opp.Pricebook2Id];
        if(pbl.size()<1){ return; }        
        PriceBook2 pb = pbl.get(0);
        if(opp.RecordTypeId == AppSetup.recordTypeSS){
            if(pb==null || pb.Punti_Consiglio_SS__c == null || pb.Punti_Consiglio_SS__c <= 0){
                return;
            }
            punti = pb.Punti_Consiglio_SS__c;
        } else if (opp.RecordTypeId == AppSetup.recordTypeSG){ 
            if(pb == null || pb.Tipo_Listino__c != 'Punti consiglio'){ 	return;  }
            List<OpportunityLineItem> items = [Select PricebookEntry.Punti_consiglio__c from OpportunityLineItem where OpportunityId =:opp.Id];
            for(OpportunityLineItem opli : items){ punti += (opli.PricebookEntry.Punti_consiglio__c == null ? 0 : opli.PricebookEntry.Punti_consiglio__c); }
        } // else {  return;  }
        // Specialista
        List<Ruolo_degli_Specialisti_Collaboratori__c> refs = [Select Referente__c from Ruolo_degli_Specialisti_Collaboratori__c 
                                                               where Opportunita__c = :opp.Id 
                                                               and (Ruolo__c = 'Specialista' or Ruolo__c = 'Specialista che consiglia')];                 
        if(refs.size() > 0){
            String refId = refs.get(0).Referente__c;
            Contact c = [SELECT Id, Punti_consiglio_totali_SS__c, Punti_consiglio_totali_SG__c  FROM Contact where Id = :refId].get(0);
            if(opp.RecordTypeId == AppSetup.recordTypeSS){
                double mpt = c.Punti_consiglio_totali_SS__c;
                c.Punti_consiglio_totali_SS__c = (mpt == null ? punti : (mpt + punti));
                update(c);
            } else if (opp.RecordTypeId == AppSetup.recordTypeSG){ 
                double mpt = c.Punti_consiglio_totali_SG__c;
                c.Punti_consiglio_totali_SG__c = (mpt == null ? punti : (mpt + punti));
                update(c);            
            }
            return;
        }
        // Professional
        if(opp.Ospedale_Punto_prelievo__c !=null){
            Account a = [SELECT Id, Punti_consiglio_totali_SS__c, Punti_consiglio_totali_SG__c FROM Account where Id = :opp.Ospedale_Punto_prelievo__c].get(0);
            if(opp.RecordTypeId == AppSetup.recordTypeSS){
                double mpt = a.Punti_consiglio_totali_SS__c;
                a.Punti_consiglio_totali_SS__c = (mpt == null ? punti : (mpt + punti));
                update(a);
            } else if (opp.RecordTypeId == AppSetup.recordTypeSG){ 
                double mpt = a.Punti_consiglio_totali_SG__c;
                a.Punti_consiglio_totali_SG__c = (mpt == null ? punti : (mpt + punti));
                update(a);
            }
            return;
        }  
    }
}