Sorgente/.apex/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Listino__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Listino prezzi</label>
        <referenceTo>Pricebook2</referenceTo>
        <relationshipLabel>Account</relationshipLabel>
        <relationshipName>Account</relationshipName>
        <type>Lookup</type>
    </fields>
    <recordTypes>
        <fullName>Standard</fullName>
        <active>true</active>
        <label>Altro</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

Sorgente/src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Listino_prezzi__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Listino prezzi</label>
        <referenceTo>Pricebook2</referenceTo>
        <relationshipLabel>Referenti</relationshipLabel>
        <relationshipName>Referenti</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

Sorgente/src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Ospedale_Punto_prelievo__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Ospedale/Punto prelievo</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Professional</value>
            </filterItems>
            <filterItems>
                <field>Account.Struttura_abilitata_ai_parti__c</field>
                <operation>equals</operation>
                <value>Si</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Opportunità (Ospedale/Punto prelievo)</relationshipLabel>
        <relationshipName>Opportunit1</relationshipName>
        <type>Lookup</type>
    </fields>
    <recordTypes>
        <fullName>SG</fullName>
        <active>true</active>
        <businessProcess>SG</businessProcess>
        <label>SG</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

Sorgente/src/classes/AssegnaListino.cls
public class AssegnaListino {
	@InvocableMethod
    public static void AssegnaListino(List<Opportunity> source){
        /*
        Listino Opportunità: -> 1°:'Ospedale/Punto Prelievo' (and has listino), 
                          2°:'Ruolo degli specialisti colaboratori' (and has listino), 
                          3°: standard price book
                        when: status 'I.A. Prelievo' (SG)
		*/
        if(source == null || source.size() <=0){
            return;
        }
        Opportunity opp = [Select Id, Pricebook2Id, Ospedale_Punto_prelievo__r.Listino__c from Opportunity where Id= :source.get(0).Id].get(0);
        if(opp.Pricebook2Id != null){
            // c'è già, va bene così
            return; 
        }
        
        List<OpportunityContactRole> ocrs = [Select Id, Contact.Listino_prezzi__c from OpportunityContactRole where Contact.Listino_prezzi__c != null and OpportunityId =:source.get(0).Id];
        if(ocrs != null && ocrs.size()>0){
            opp.Pricebook2Id = ocrs[0].Contact.Listino_prezzi__c;
            update(opp);
        	return;
        }
        
        if(opp.Ospedale_Punto_prelievo__r != null && opp.Ospedale_Punto_prelievo__r.Listino__c != null){
            opp.Pricebook2Id = opp.Ospedale_Punto_prelievo__r.Listino__c;
            update(opp);
        	return;
        }
        
        if (Test.isRunningTest()) {
            opp.Pricebook2Id = Test.getStandardPricebookId();
    	} else {
        	opp.Pricebook2Id = [select id, name from Pricebook2 where isStandard = true limit 1].Id;
    	}
      	update(opp);
        
    }
}