Sorgente/.apex/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Agente__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Agente</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>User.Profile.Name</field>
                <operation>equals</operation>
                <value>Force.com - App Subscription User (KAM)</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>User</referenceTo>
        <relationshipName>Account</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Conferma_perdita_SG__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Conferma perdita SG</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Conferma_perdita_SS__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Conferma perdita SS</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Listino__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Listino prezzi</label>
        <referenceTo>Pricebook2</referenceTo>
        <relationshipLabel>Account</relationshipLabel>
        <relationshipName>Account</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Motivazione_perdita_SG__c</fullName>
        <label>Motivazione perdita SG</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Prezzo prodotti</fullName>
                </value>
                <value>
                    <fullName>Qualità prodotti</fullName>
                </value>
                <value>
                    <fullName>Qualità servizio</fullName>
                </value>
                <value>
                    <fullName>Listino incompleto</fullName>
                </value>
                <value>
                    <fullName>Altro</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Motivazione_perdita_SS__c</fullName>
        <label>Motivazione perdita SS</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Pro-donazione</fullName>
                </value>
                <value>
                    <fullName>Esclusività con competitor</fullName>
                </value>
                <value>
                    <fullName>Qualità prodotto</fullName>
                </value>
                <value>
                    <fullName>Qualità servizio</fullName>
                </value>
                <value>
                    <fullName>Prezzo servizio al paziente</fullName>
                </value>
                <value>
                    <fullName>Punti consiglio bassi</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Status_SG__c</fullName>
        <label>Status SG</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Aperto</fullName>
                </value>
                <value>
                    <fullName>Perso</fullName>
                </value>
                <value>
                    <fullName>Da affiliare o associare</fullName>
                </value>
                <value>
                    <fullName>Da riaffiliare</fullName>
                </value>
                <value>
                    <fullName>Da riassociare</fullName>
                </value>
                <value>
                    <fullName>Associato</fullName>
                </value>
                <value>
                    <fullName>Affiliato</fullName>
                </value>
                <value>
                    <fullName>Inattivo</fullName>
                </value>
                <value>
                    <fullName>Associato perso</fullName>
                </value>
                <value>
                    <fullName>Affiliato perso</fullName>
                </value>
                <value>
                    <fullName>IA prodotto</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Status_SS__c</fullName>
        <label>Status SS</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Aperto</fullName>
                </value>
                <value>
                    <fullName>Perso</fullName>
                </value>
                <value>
                    <fullName>Da affiliare o associare</fullName>
                </value>
                <value>
                    <fullName>Da riaffiliare</fullName>
                </value>
                <value>
                    <fullName>Da riassociare</fullName>
                </value>
                <value>
                    <fullName>Associato</fullName>
                </value>
                <value>
                    <fullName>Affiliato</fullName>
                </value>
                <value>
                    <fullName>Inattivo</fullName>
                </value>
                <value>
                    <fullName>Associato perso</fullName>
                </value>
                <value>
                    <fullName>Affiliato perso</fullName>
                </value>
                <value>
                    <fullName>IA prodotto</fullName>
                </value>
                <value>
                    <fullName>Cliente</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Struttura_abilitata_ai_parti__c</fullName>
        <label>Struttura abilitata ai parti</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Da verificare</fullName>
                    <default>true</default>
                    <label>Da verificare</label>
                </value>
                <value>
                    <fullName>Si</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <recordTypes>
        <fullName>Professional</fullName>
        <active>true</active>
        <label>Professional</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

Sorgente/src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Conferma_perdita_SG__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Conferma perdita SG</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Conferma_perdita_SS__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Conferma perdita SS</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Listino_prezzi__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Listino prezzi</label>
        <referenceTo>Pricebook2</referenceTo>
        <relationshipLabel>Referenti</relationshipLabel>
        <relationshipName>Referenti</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Motivazione_perdita_SG__c</fullName>
        <label>Motivazione perdita SG</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Prezzo prodotti</fullName>
                </value>
                <value>
                    <fullName>Qualità prodotti</fullName>
                </value>
                <value>
                    <fullName>Qualità servizio</fullName>
                </value>
                <value>
                    <fullName>Listino incompleto</fullName>
                </value>
                <value>
                    <fullName>Altro</fullName>
                </value>
                <value>
                    <fullName>Inattivo</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Status_SG__c</fullName>
        <label>Status SG</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Da affiliare o associare</fullName>
                </value>
                <value>
                    <fullName>Da riaffiliare</fullName>
                </value>
                <value>
                    <fullName>Da riassociare</fullName>
                </value>
                <value>
                    <fullName>Associato</fullName>
                </value>
                <value>
                    <fullName>Affiliato</fullName>
                </value>
                <value>
                    <fullName>Inattivo</fullName>
                </value>
                <value>
                    <fullName>Associato perso</fullName>
                </value>
                <value>
                    <fullName>Affiliato perso</fullName>
                </value>
                <value>
                    <fullName>Perso</fullName>
                </value>
                <value>
                    <fullName>IA prodotto</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Status_SS__c</fullName>
        <label>Status SS</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Da affiliare o associare</fullName>
                </value>
                <value>
                    <fullName>Da riaffiliare</fullName>
                </value>
                <value>
                    <fullName>Da riassociare</fullName>
                </value>
                <value>
                    <fullName>Associato</fullName>
                </value>
                <value>
                    <fullName>Affiliato</fullName>
                </value>
                <value>
                    <fullName>Inattivo</fullName>
                </value>
                <value>
                    <fullName>Associato perso</fullName>
                </value>
                <value>
                    <fullName>Affiliato perso</fullName>
                </value>
                <value>
                    <fullName>Perso</fullName>
                </value>
                <value>
                    <fullName>IA prodotto</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <recordTypes>
        <fullName>Specialista</fullName>
        <active>true</active>
        <description>Uno medico con caratteristiche da influencer</description>
        <label>Specialista</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

Sorgente/src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Agente__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Agente</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>User.Profile.Name</field>
                <operation>equals</operation>
                <value>Force.com - App Subscription User (KAM)</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>User</referenceTo>
        <relationshipName>Opportunit</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Ospedale_Punto_prelievo__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Ospedale/Punto prelievo</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Professional</value>
            </filterItems>
            <filterItems>
                <field>Account.Struttura_abilitata_ai_parti__c</field>
                <operation>equals</operation>
                <value>Si</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Opportunità (Ospedale/Punto prelievo)</relationshipLabel>
        <relationshipName>Opportunit1</relationshipName>
        <type>Lookup</type>
    </fields>
    <recordTypes>
        <fullName>SG</fullName>
        <active>true</active>
        <businessProcess>SG</businessProcess>
        <label>SG</label>
    </recordTypes>
    <recordTypes>
        <fullName>SS</fullName>
        <active>true</active>
        <businessProcess>SS</businessProcess>
        <label>SS</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

Sorgente/.apex/src/objects/Pricebook2.object
<CustomObject>
    <fields>
        <fullName>Punti_Consiglio_SS__c</fullName>
        <label>Punti Consiglio SS</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Tipo_Listino__c</fullName>
        <label>Tipo listino</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Punti consiglio</fullName>
                </value>
                <value>
                    <fullName>Acquisto</fullName>
                </value>
                <value>
                    <fullName>Libero</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ReadSelect</sharingModel>
</CustomObject>

Sorgente/.apex/src/objects/Ruolo_degli_Specialisti_Collaboratori__c.object
<CustomObject>
    <fields>
        <fullName>Opportunita__c</fullName>
        <label>Opportunità</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Ruoli degli Specialisti/Collaboratori</relationshipLabel>
        <relationshipName>Ruoli_degli_Specialisti_Collaboratori</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Referente__c</fullName>
        <label>Referente</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.RecordType.DeveloperName</field>
                <operation>equals</operation>
                <value>Specialista</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Ruoli degli Specialisti/Collaboratori</relationshipLabel>
        <relationshipName>Ruoli_degli_Specialisti_Collaboratori</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Ruolo__c</fullName>
        <label>Ruolo</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Specialista che consiglia</fullName>
                </value>
                <value>
                    <fullName>Specialista</fullName>
                </value>
                <value>
                    <fullName>Collaboratore che consiglia</fullName>
                </value>
                <value>
                    <fullName>Programma Amico</fullName>
                </value>
                <value>
                    <fullName>Operatore prelievo</fullName>
                </value>
                <value>
                    <fullName>Prescrittore</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Ruolo degli Specialisti/Collaboratori</label>
    <nameField>
        <displayFormat>A-{0000000}</displayFormat>
        <label>Nome Ruolo degli Specialisti/Collaborato</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Ruoli degli Specialisti/Collaboratori</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Sorgente/.apex/src/classes/TestStatus.cls
@isTest
public class TestStatus {
    private static testMethod void testStatus(){
       /*
        UpdateStatusAccount usa = new UpdateStatusAccount();
        UpdateStatusReferenti usr = new UpdateStatusReferenti();
        
        Account a = new Account();
        a.FirstName = 'Unit';
        a.LastName = 'Test User';
        a.PersonEmail = 'ssineriz@gmail.com';
        a.RecordTypeId = AppSetup.recordTypePersonAccount;
        a.Agente__c = [select Id from User where Name='TestKam'].get(0).Id;
        insert(a);
        
        PriceBook2 pbl = new PriceBook2();
        pbl.Tipo_Listino__c = 'Libero';
        pbl.Name = 'Unit Test Listino Libero';
        insert(pbl);
        
        PriceBook2 pbp = new PriceBook2();
        pbp.Tipo_Listino__c = 'Punti consiglio';
        pbp.Name = 'Unit Test Listino Punti';
        pbp.Punti_Consiglio_SS__c = 10;
        insert(pbp);
        
        Account p = new Account();
        p.Name = 'Unit Test Professional';
        p.RecordTypeId = AppSetup.recordTypeProfessional;
        p.Struttura_abilitata_ai_parti__c = 'Si';
        insert(p);
        
        Contact s = new Contact();
        s.AccountId = p.Id;
        s.FirstName = 'Unit';
        s.LastName = 'Test Specialista';
        s.RecordTypeId = AppSetup.recordTypeSpecialista;      

        // b.Motivazione_perdita_SG__c, SS
        // Conferma_perdita_SG__c
        // Status_SG__c
        // Listino_prezzi__c, Listino__c

        // 1 - Inattivo, Listino Libero
        p.Status_SG__c = 'Inattivo';
        p.Status_SS__c = 'Inattivo';
        s.Status_SG__c = 'Inattivo';
        s.Status_SS__c = 'Inattivo';
        p.Listino__c = pbl.Id;
        s.Listino_prezzi__c = pbl.Id;
        
        update(p);
        insert(s);
        
        usa.execute();
        usr.execute();

        
        // Create some opportunities
        Opportunity o1 = new Opportunity();
        o1.RecordTypeId = AppSetup.recordTypeSG;
        o1.Name = 'Opportunita Unit Test SG Professional';
        o1.AccountId = a.Id;
        o1.StageName = 'Aperto';
        o1.CloseDate = Date.today();
        o1.Ospedale_Punto_prelievo__c = p.id;
        insert(o1);
        
        Opportunity o2 = new Opportunity();
        o2.RecordTypeId = AppSetup.recordTypeSS;
        o2.Name = 'Opportunita Unit Test SS Professional';
        o2.AccountId = a.Id;
        o2.StageName = 'Aperto';
        o2.CloseDate = Date.today();
        o2.Ospedale_Punto_prelievo__c = p.id;
        o2.Pricebook2Id = pbp.Id;
        insert(o2);        

        Opportunity o3 = new Opportunity();
        o3.RecordTypeId = AppSetup.recordTypeSS;
        o3.Name = 'Opportunita Unit Test SS Specialista';
        o3.AccountId = a.Id;
        o3.StageName = 'Aperto';
        o3.CloseDate = Date.today();
        o3.Pricebook2Id = pbl.Id;
        insert(o3);
        
        Ruolo_degli_Specialisti_Collaboratori__c rs = new Ruolo_degli_Specialisti_Collaboratori__c();
        rs.Referente__c = s.Id;
        rs.Ruolo__c = 'Specialista';
        rs.Opportunita__c = o3.Id;
        insert(rs);

        Opportunity o4 = new Opportunity();
        o4.RecordTypeId = AppSetup.recordTypeSG;
        o4.Name = 'Opportunita Unit Test SG Specialista';
        o4.AccountId = a.Id;
        o4.StageName = 'Aperto';
        o4.CloseDate = Date.today();
        o4.Pricebook2Id = pbp.Id;
        insert(o4);
        
        rs = new Ruolo_degli_Specialisti_Collaboratori__c();
        rs.Referente__c = s.Id;
        rs.Ruolo__c = 'Specialista';
        rs.Opportunita__c = o4.Id;
        insert(rs);        
        
        // with opportunities
        usa.execute();
        usr.execute();
        
        p.Status_SG__c = 'Affiliato';
        p.Status_SS__c = 'Affiliato';
        s.Status_SG__c = 'Affiliato';
        s.Status_SS__c = 'Affiliato';       
        
        update(p);
        update(s);

        usa.execute();
        usr.execute(); 

        // listino punti
        p.Listino__c = pbp.Id;
        s.Listino_prezzi__c = pbp.Id;      
        update(p);
        update(s);
        usa.execute();
        usr.execute();
        
        // perso
        p.Conferma_perdita_SG__c = true;
        p.Conferma_perdita_SS__c = true;
        s.Conferma_perdita_SG__c = true;
        s.Conferma_perdita_SS__c = true;
        update(p);
        update(s);
        usa.execute();
        usr.execute(); 
        
        // Inattivo
        p.Motivazione_perdita_SG__c = 'Inattivo';
        p.Motivazione_perdita_SS__c = 'Inattivo';
        s.Motivazione_perdita_SG__c = 'Inattivo';
        s.Motivazione_perdita_SS__c = 'Inattivo';
        update(p);
        update(s);
        usa.execute();
        usr.execute(); 
        
        // Punti Consiglio
        AssegnaPuntiConsiglio.AssegnaPuntiConsiglio(null);
        
        Product2 prod = new Product2();
        prod.Name = 'Unit Test Prodotto';
        prod.RecordTypeId = AppSetup.recordTypeServizi;
        insert prod;
        
        PricebookEntry pbe = new PricebookEntry();
        pbe.Pricebook2Id = Test.getStandardPricebookId();
        pbe.UnitPrice = 10;
        pbe.IsActive = true;
        pbe.Product2Id = prod.Id;
        insert(pbe);
        
        List<Opportunity> opps = new List<Opportunity>();
        opps.add(o1);
        AssegnaPuntiConsiglio.AssegnaPuntiConsiglio(opps);
        o1.Pricebook2Id = Test.getStandardPricebookId();
        update(o1);

        OpportunityLineItem oli = new OpportunityLineItem();
        oli.OpportunityId = o1.Id;
        oli.PricebookEntryId = pbe.Id;
        oli.Quantity = 2;
        oli.TotalPrice = 25;
        Insert(oli);

        AssegnaPuntiConsiglio.AssegnaPuntiConsiglio(opps);
        opps.clear(); opps.add(o2);
        AssegnaPuntiConsiglio.AssegnaPuntiConsiglio(opps);
        opps.clear(); opps.add(o3);
        AssegnaPuntiConsiglio.AssegnaPuntiConsiglio(opps);
        opps.clear(); opps.add(o4);
        AssegnaPuntiConsiglio.AssegnaPuntiConsiglio(opps);
*/
    }
}