Sorgente/.apex/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Agente__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Agente</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>User.Profile.Name</field>
                <operation>equals</operation>
                <value>Force.com - App Subscription User (KAM)</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>User</referenceTo>
        <relationshipName>Account</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Origine__c</fullName>
        <label>Origine</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Amici/conoscenti</fullName>
                </value>
                <value>
                    <fullName>Corso Preparto</fullName>
                </value>
                <value>
                    <fullName>Siti e app satellite</fullName>
                </value>
                <value>
                    <fullName>Social media</fullName>
                </value>
                <value>
                    <fullName>Giornali/riviste</fullName>
                </value>
                <value>
                    <fullName>Fiere e Convegni</fullName>
                </value>
                <value>
                    <fullName>Specialista</fullName>
                </value>
                <value>
                    <fullName>KAM</fullName>
                </value>
                <value>
                    <fullName>Siti extra gruppo</fullName>
                </value>
                <value>
                    <fullName>Motore di ricerca</fullName>
                </value>
                <value>
                    <fullName>Pieghevole</fullName>
                </value>
                <value>
                    <fullName>Programma Amico</fullName>
                </value>
                <value>
                    <fullName>Collaboratore</fullName>
                </value>
                <value>
                    <fullName>Altro</fullName>
                </value>
                <value>
                    <fullName>Da verificare</fullName>
                </value>
                <value>
                    <fullName>Professional</fullName>
                </value>
                <value>
                    <fullName>Cross selling</fullName>
                </value>
                <value>
                    <fullName>Già cliente</fullName>
                </value>
                <value>
                    <fullName>Cross selling - Aurora</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Riconosci_ad_agente_del_referente__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Riconosci ad agente dei referenti</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

Sorgente/src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Origine__c</fullName>
        <label>Origine</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Amici/conoscenti</fullName>
                </value>
                <value>
                    <fullName>Corso Preparto</fullName>
                </value>
                <value>
                    <fullName>Siti e app satellite</fullName>
                </value>
                <value>
                    <fullName>Social media</fullName>
                </value>
                <value>
                    <fullName>Fiere e Convegni</fullName>
                </value>
                <value>
                    <fullName>Specialista</fullName>
                </value>
                <value>
                    <fullName>Professional</fullName>
                </value>
                <value>
                    <fullName>KAM</fullName>
                </value>
                <value>
                    <fullName>Siti extra gruppo</fullName>
                </value>
                <value>
                    <fullName>Motore di ricerca</fullName>
                </value>
                <value>
                    <fullName>Pieghevole</fullName>
                </value>
                <value>
                    <fullName>Collaboratore</fullName>
                </value>
                <value>
                    <fullName>Altro</fullName>
                </value>
                <value>
                    <fullName>Da verificare</fullName>
                </value>
                <value>
                    <fullName>Candidatura spontanea</fullName>
                </value>
                <value>
                    <fullName>Società di selezione</fullName>
                </value>
                <value>
                    <fullName>Istituto di formazione</fullName>
                </value>
                <value>
                    <fullName>Campagna interna</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <recordTypes>
        <fullName>Collaboratore</fullName>
        <active>true</active>
        <description>Un collaboratore di Sorgente o Sorgente Genetica</description>
        <label>Collaboratore</label>
    </recordTypes>
    <recordTypes>
        <fullName>Specialista</fullName>
        <active>true</active>
        <description>Uno medico con caratteristiche da influencer</description>
        <label>Specialista</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

Sorgente/src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Agente__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Agente</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>User.Profile.Name</field>
                <operation>equals</operation>
                <value>Force.com - App Subscription User (KAM)</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>User</referenceTo>
        <relationshipName>Opportunit</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Operatore_prelievo__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Operatore prelievo</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.Categoria_collaboratore__c</field>
                <operation>equals</operation>
                <value>Operatore prelievo</value>
            </filterItems>
            <filterItems>
                <field>$Source.Provincia_spedizione__c</field>
                <operation>equals</operation>
                <valueField>Contact.MailingState</valueField>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Prelievi effettuati</relationshipLabel>
        <relationshipName>Opportunit</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Origine__c</fullName>
        <label>Origine</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Altro</fullName>
                </value>
                <value>
                    <fullName>Amici/conoscenti</fullName>
                </value>
                <value>
                    <fullName>Collaboratore</fullName>
                </value>
                <value>
                    <fullName>Corso Preparto</fullName>
                </value>
                <value>
                    <fullName>Cross selling</fullName>
                </value>
                <value>
                    <fullName>Cross selling - Aurora</fullName>
                </value>
                <value>
                    <fullName>Da verificare</fullName>
                </value>
                <value>
                    <fullName>Fiera</fullName>
                    <label>Fiere e Convegni</label>
                </value>
                <value>
                    <fullName>Già cliente</fullName>
                </value>
                <value>
                    <fullName>Giornali/riviste</fullName>
                </value>
                <value>
                    <fullName>KAM</fullName>
                </value>
                <value>
                    <fullName>Motore di ricerca</fullName>
                </value>
                <value>
                    <fullName>Pieghevole</fullName>
                </value>
                <value>
                    <fullName>Professional</fullName>
                </value>
                <value>
                    <fullName>Programma Amico</fullName>
                </value>
                <value>
                    <fullName>Siti e app satellite</fullName>
                </value>
                <value>
                    <fullName>Siti extra gruppo</fullName>
                </value>
                <value>
                    <fullName>Social media</fullName>
                </value>
                <value>
                    <fullName>Specialista</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Ospedale_Punto_prelievo__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Ospedale/Punto prelievo</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Professional</value>
            </filterItems>
            <filterItems>
                <field>Account.Struttura_abilitata_ai_parti__c</field>
                <operation>equals</operation>
                <value>Si</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Opportunità (Ospedale/Punto prelievo)</relationshipLabel>
        <relationshipName>Opportunit1</relationshipName>
        <type>Lookup</type>
    </fields>
    <recordTypes>
        <fullName>SG</fullName>
        <active>true</active>
        <businessProcess>SG</businessProcess>
        <label>SG</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

Sorgente/.apex/src/objects/Ruolo_degli_Specialisti_Collaboratori__c.object
<CustomObject>
    <fields>
        <fullName>Opportunita__c</fullName>
        <label>Opportunità</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Ruoli degli Specialisti/Collaboratori</relationshipLabel>
        <relationshipName>Ruoli_degli_Specialisti_Collaboratori</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Referente__c</fullName>
        <label>Referente</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.RecordType.DeveloperName</field>
                <operation>equals</operation>
                <value>Specialista</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Ruoli degli Specialisti/Collaboratori</relationshipLabel>
        <relationshipName>Ruoli_degli_Specialisti_Collaboratori</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Ruolo__c</fullName>
        <label>Ruolo</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Specialista che consiglia</fullName>
                </value>
                <value>
                    <fullName>Specialista</fullName>
                </value>
                <value>
                    <fullName>Collaboratore che consiglia</fullName>
                </value>
                <value>
                    <fullName>Programma Amico</fullName>
                </value>
                <value>
                    <fullName>Operatore prelievo</fullName>
                </value>
                <value>
                    <fullName>Prescrittore</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Ruolo degli Specialisti/Collaboratori</label>
    <nameField>
        <displayFormat>A-{0000000}</displayFormat>
        <label>Nome Ruolo degli Specialisti/Collaborato</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Ruoli degli Specialisti/Collaboratori</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Sorgente/.apex/src/classes/ImpostaAgenteOpportunita.cls
public class ImpostaAgenteOpportunita {
	@InvocableMethod
    public static void ImpostaAgenteOpportunita(List<Opportunity> source){
        if(source == null || source.size() <=0){
            return;
        }
        Opportunity opp = [Select Id, Agente__c, AccountId, Ospedale_Punto_prelievo__c, RecordTypeId, Origine__c, Operatore_prelievo__c, Operatore_prelievo__r.OwnerId from Opportunity where Id= :source.get(0).Id].get(0);
                
        List<OpportunityContactRole> pas = [select ContactId, Contact.OwnerId from OpportunityContactRole where Role = 'Programma Amico' and OpportunityId=:opp.Id]; 
        if(pas.size()>0){
            opp.Agente__c = pas[0].Contact.OwnerId;
            update(opp);
        	return;
        }

        Account pa = [Select Id, Agente__c from Account where Id =:opp.AccountId].get(0);
        if(pa.Agente__c != null){
            opp.Agente__c = pa.Agente__c;
            update(opp);
        	return;
        }
		
        // Solo SG: If Origine__c dell'opportunità = 'Collaboratore' and Operatore prelievo in Ruolo_degli_Specialisti_Collaboratori__c -> Coll.Contact.OwnerId
        if(opp.RecordTypeId == AppSetup.recordTypeSG && opp.Origine__c == 'Collaboratore'){
            /*
            List<Ruolo_degli_Specialisti_Collaboratori__c> ops = [select Id, Referente__c, Referente__r.OwnerId from Ruolo_degli_Specialisti_Collaboratori__c 
                                                                  where Ruolo__c = 'Operatore prelievo' and Opportunita__c=:opp.Id]; 
            if(ops.size()>0){
                opp.Agente__c = ops[0].Referente__r.OwnerId;
                update(opp);
                return;
            } 
			*/
            if(opp.Operatore_prelievo__c != null && opp.Operatore_prelievo__r.OwnerId!=null){
                opp.Agente__c = opp.Operatore_prelievo__r.OwnerId;
                update(opp);
                return;
            }
        }
        // If recordtype == SG and [Riconosci_ad_agente_del_referente__c]==false
        if(opp.RecordTypeId == AppSetup.recordTypeSG && opp.Ospedale_Punto_prelievo__c !=null){
            Account acc = [SELECT Id, OwnerId, Riconosci_ad_agente_del_referente__c FROM Account where Id = :opp.Ospedale_Punto_prelievo__c].get(0);
            if(acc.OwnerId != null && acc.Riconosci_ad_agente_del_referente__c == false){
              	opp.Agente__c = acc.OwnerId;
                update(opp);
        		return;              
            }
        }  
        
        List<Ruolo_degli_Specialisti_Collaboratori__c> scc = [Select Id, Referente__c from Ruolo_degli_Specialisti_Collaboratori__c 
                             where Opportunita__c = :opp.Id 
                             and Ruolo__c = 'Specialista che consiglia'];
        
        if(scc.size() > 0){
            Contact cnt = [Select Id, OwnerId from Contact where Id =: scc.get(0).Referente__c].get(0);
            if(cnt.OwnerId != null){
              	opp.Agente__c = cnt.OwnerId;
                update(opp);
        		return;              
            }
        }
        
        List<Ruolo_degli_Specialisti_Collaboratori__c> sc = [Select Id, Referente__c from Ruolo_degli_Specialisti_Collaboratori__c 
                             where Opportunita__c = :opp.Id 
                             and Ruolo__c = 'Specialista'];
        
        if(sc.size() > 0){
            Contact cnt = [Select Id, OwnerId from Contact where Id =: sc.get(0).Referente__c].get(0);
            if(cnt.OwnerId != null){
              	opp.Agente__c = cnt.OwnerId;
                update(opp);
        		return;              
            }
        }

    }
}